#!/usr/bin/env python3
"""Language Stacking: 学习库静态站点生成器（registry 驱动）

读取 languages/ 下的 markdown(prose + frontmatter) 与 data/ 下的 JSON(结构化数据),
按 languages/README.md 的语种注册表(frontmatter)泛化渲染学习库三级子站:
  learning/index.html            (hub，来自 registry)
  learning/{lang}/index.html     (每 active 语种的索引，来自 {lang}/README.md + modules)
  learning/{lang}/{module}.html  (每 ready 模块页，prose 来自 {lang}/{module}.md，
                                 结构化数据由 meta.kind 对应 KIND_VIEWS 渲染)

用法:
  conda activate hy_py312
  python "Language Stacking-Linguistic Weaving/web/build_learning.py" [--validate] [--db] [--check]

功能:
  --validate  校验知识源（frontmatter/模块一致性/双语标记平衡/JSON schema/链接解析）
  --db        同步 sqlite 查询索引 languages/data/learning.db（语言+模块+音图+词表+织网库）
  --check     源校验 + 产物校验（存在性/关键组件/标签平衡/陈旧产物检测）

标准库之外仅依赖 markdown 包与(可选)pytest。内容数据不硬编码：一律来自 languages/**。
"""
import argparse
import html
import json
import os
import re
import sys
import urllib.parse

try:
    import markdown
except ImportError as exc:  # pragma: no cover
    sys.exit(f"[build_learning] 缺少依赖: {exc}  (请 conda activate hy_py312)")

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DOMAIN = os.path.join(REPO, "Language Stacking-Linguistic Weaving")
LANG    = os.path.join(DOMAIN, "languages")
DATA    = os.path.join(LANG, "data")
OUT     = os.path.join(REPO, "docs", "language_stacking", "learning")
CSS_SRC = os.path.join(HERE, "css", "learning.css")
CSS_OUT = os.path.join(OUT, "css", "learning.css")
GLOSSARY_MD   = os.path.join(LANG, "glossary.md")
GLOSSARY_JSON = os.path.join(DATA, "core_glossary.json")

MD = markdown.Markdown(extensions=["tables", "fenced_code", "attr_list", "toc", "sane_lists"])


# ── shell 模板 ────────────────────────────────────────────────
PAGE = """<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=LXGW+WenKai:wght@400;700&family=Inter:wght@400;500;600;700&family=Noto+Serif+JP:wght@400;600&family=Noto+Sans+JP:wght@400;500&family=EB+Garamond:ital,wght@0,400;0,500;1,400&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{css}">
</head>
<body class="{initlang}">
<header class="nav">
  <div class="nav-brand"><span data-zh>语言叠织</span><span data-en>Language Stacking</span><span class="sub">&middot; 学习库 Learning</span></div>
  <div class="nav-right">
    <a class="nav-home" href="{home}">{home_label}</a>
    <div class="voice-wrap">
      <label class="voice-label" for="voice-picker"><span data-zh>声线</span><span data-en>voice</span></label>
      <select id="voice-picker" class="voice-picker" aria-label="voice selector"></select>
      <button id="voice-status" class="voice-status" type="button" title="重新检测声线"><span data-zh>语音检测中…</span><span data-en>scanning…</span></button>
      <label class="voice-label" for="tempo-picker"><span data-zh>语速</span><span data-en>tempo</span></label>
      <select id="tempo-picker" class="voice-picker" aria-label="tempo selector">
        <option value="0.7">慢 · slow</option>
        <option value="1.0" selected>中 · mid</option>
        <option value="1.4">快 · fast</option>
      </select>
    </div>
    <div class="lang-toggle" aria-label="language">
      <button data-lang="zh" type="button">中</button>
      <button data-lang="en" type="button">EN</button>
    </div>
  </div>
</header>
<main>
{hero}
<div class="wrap">
{body}
</div>
</main>
<footer class="footer">
  <p><span data-zh>《语言叠织 · Language Stacking》 语种根本 · 所有学习与使用不离根本</span><span data-en>Language Stacking — per-language Roots · learning and use stay rooted</span></p>
  <p class="note"><span data-zh>本页由 build_learning.py 从 languages/ 知识源自动生成 · 内容以知识库为单一来源</span><span data-en>Generated by build_learning.py from the languages/ knowledge base · single source of truth</span></p>
</footer>
<div id="kana-modal" class="kana-modal" hidden>
  <div class="km-mask" data-km-close="1"></div>
  <div class="km-card" role="dialog" aria-modal="true" aria-labelledby="km-title">
    <button class="km-x" type="button" data-km-close="1" aria-label="close">&times;</button>
    <h3 class="km-title" id="km-title"></h3>
    <div class="km-stage" id="km-stage">
      <svg class="km-lines" id="km-lines" aria-hidden="true"></svg>
      <div class="km-center" id="km-center"></div>
      <div class="km-node km-n-shape" data-sat="shape"></div>
      <div class="km-node km-n-word" data-sat="word"></div>
      <div class="km-node km-n-sense" data-sat="sense"></div>
      <div class="km-node km-n-root" data-sat="root"></div>
      <div class="km-node km-n-law" data-sat="law"></div>
    </div>
    <div class="km-sent" id="km-sent"></div>
  </div>
</div>
<script>
(function () {{
  const key = 'ls-lang';
  const saved = (() => {{ try {{ return localStorage.getItem(key); }} catch (e) {{ return null; }} }})();
  document.body.classList.add(saved === 'en' ? 'lang-en' : 'lang-zh');
  function set(lang) {{
    document.body.classList.toggle('lang-en', lang === 'en');
    document.body.classList.toggle('lang-zh', lang === 'zh');
    document.querySelectorAll('.lang-toggle button').forEach(function (b) {{
      b.classList.toggle('active', b.getAttribute('data-lang') === lang);
    }});
    try {{ localStorage.setItem(key, lang); }} catch (e) {{}}
  }}
  set(document.body.classList.contains('lang-en') ? 'en' : 'zh');
  document.querySelectorAll('.lang-toggle button').forEach(function (b) {{
    b.addEventListener('click', function () {{ set(b.getAttribute('data-lang')); }});
  }});
  window.addEventListener('scroll', function () {{
    document.querySelector('header.nav').classList.toggle('scrolled', window.scrollY > 8);
  }});
  window._lastKanaVoice = null;
  function kanaVoiceScore(v) {{
    var n = (v.name || '').toLowerCase();
    if (v.localService) return 30;
    if (n.indexOf('desktop') >= 0) return 20;
    if (n.indexOf('natural') >= 0 || n.indexOf('neural') >= 0) return 10;
    if (n.indexOf('online') >= 0 || n.indexOf('premium') >= 0) return 8;
    if (n.indexOf('google') >= 0) return 6;
    return 1;
  }}
  function jaVoices() {{
    try {{
      var raw = speechSynthesis.getVoices();
      var arr = [];
      for (var i = 0; i < raw.length; i++) arr.push(raw[i]);
      var vs = arr.filter(function (v) {{
        return (v.lang || '').replace(/_/g, '-').toLowerCase().indexOf('ja') === 0;
      }});
      vs.sort(function (a, b) {{ return kanaVoiceScore(b) - kanaVoiceScore(a); }});
      if (vs.length) return vs;
      var any = arr.slice().sort(function (a, b) {{ return kanaVoiceScore(b) - kanaVoiceScore(a); }});
      return any;
    }} catch (e) {{ return []; }}
  }}
  function resolveVoice(uri) {{
    if (!uri) return null;
    var vs = speechSynthesis.getVoices();
    for (var i = 0; i < vs.length; i++) {{
      if (vs[i].voiceURI === uri) return vs[i];
    }}
    return null;
  }}
  window._lastKanaVoice = null;
  try {{ window._lastKanaVoice = localStorage.getItem('ls-jp-voice') || null; }} catch (e) {{}}
  var _voiceSig = '';
  function setVoiceStatus(jaCount, total, lackText) {{
    var st = document.getElementById('voice-status');
    if (!st) return;
    window._jaVoiceCount = jaCount;
    var zh = (jaCount > 0 ? '日语声线 ' + jaCount : '未检测到日语声线') + ' · 共 ' + total;
    var en = (jaCount > 0 ? 'ja voices ' + jaCount : 'no Japanese voice') + ' · total ' + total;
    var zhNode = st.querySelector('[data-zh]'), enNode = st.querySelector('[data-en]');
    if (zhNode) zhNode.textContent = zh;
    if (enNode) enNode.textContent = en;
    st.classList.toggle('no-ja', jaCount === 0);
    st.title = lackText;
  }}
  function rescanVoices(force) {{
    if (!('speechSynthesis' in window)) {{
      setVoiceStatus(0, 0, '此浏览器不支持语音合成 speechSynthesis');
      return;
    }}
    var all = jaVoices();
    var ja = all.filter(function (v) {{ return (v.lang || '').replace(/_/g, '-').toLowerCase().indexOf('ja') === 0; }});
    var lack = ja.length
      ? ''
      : (document.body.classList.contains('lang-en')
         ? 'No Japanese TTS voice found — install one (Windows: Settings → Time & language → Language → add 日本語 and its voice; macOS: 系统设置 → 辅助功能 → 朗读内容 → 系统声音; Android/iOS: add Japanese data to Google TTS). Then tap here to rescan.'
         : '未找到可朗读日语的声线，播放会静音。Windows: 设置 → 时间和语言 → 语言 → 添加 日本語(日本) → 点击其「语音」并下载。macOS: 系统设置 → 辅助功能 → 朗读内容 → 系统声音 → 管理声音 添加 ja-JP(如 Kyoko)。安装后点这里重新检测。');
    setVoiceStatus(ja.length, all.length, lack);
    fillVoicePicker(all);
    return ja.length;
  }}
  function fillVoicePicker(vs) {{
    var pick = document.getElementById('voice-picker');
    if (!pick) return;
    var sig = (vs || []).map(function (v) {{ return v.voiceURI; }}).join('|');
    if (sig === _voiceSig && pick.options.length > 1) return;
    _voiceSig = sig;
    pick.innerHTML = '';
    var auto = document.createElement('option');
    auto.value = '';
    auto.textContent = (document.body.classList.contains('lang-en') ? 'auto (first ja voice)' : '自动（首选日语声线）');
    pick.appendChild(auto);
    vs.forEach(function (v) {{
      var o = document.createElement('option');
      o.value = v.voiceURI;
      var short = (v.name || '').replace(/^Microsoft |^Google /, '');
      var ja = (v.lang || '').replace(/_/g, '-').toLowerCase().indexOf('ja') === 0;
      var where = v.localService ? 'local' : 'online';
      o.textContent = (window._lastKanaVoice === v.voiceURI ? '✓ ' : '') + '[' + where + (ja ? '' : ' · 非日语') + '] ' + short + ' · ' + (v.lang || '');
      pick.appendChild(o);
    }});
    pick.value = (window._lastKanaVoice && pick.querySelector('option[value="' + window._lastKanaVoice.replace(/"/g, '\\"') + '"]')) ? window._lastKanaVoice : '';
    pick.addEventListener('change', function () {{
      window._lastKanaVoice = this.value || null;
      try {{ localStorage.setItem('ls-jp-voice', this.value || ''); }} catch (e) {{}}
    }});
  }}
  var vsBtn = document.getElementById('voice-status');
  if (vsBtn) vsBtn.addEventListener('click', function () {{
    rescanVoices(true);
    liaToast(document.body.classList.contains('lang-en')
      ? 'Rescanned ' + window._jaVoiceCount + ' Japanese voice(s)'
      : '重新检测：日语声线 ' + window._jaVoiceCount + ' 个');
  }});
  function resolveTempo() {{
    try {{ var v = parseFloat(localStorage.getItem('ls-jp-tempo') || ''); if (isFinite(v) && v > 0) return v; }} catch (e) {{}}
    return 1.0;
  }}
  var tempoPick = document.getElementById('tempo-picker');
  if (tempoPick) {{
    tempoPick.value = String(resolveTempo());
    tempoPick.addEventListener('change', function () {{
      try {{ localStorage.setItem('ls-jp-tempo', this.value || ''); }} catch (e) {{}}
    }});
  }}
  function liaToast(msg) {{
    var t = document.getElementById('lia-toast');
    if (!t) {{
      t = document.createElement('div');
      t.id = 'lia-toast';
      t.className = 'lia-toast';
      document.body.appendChild(t);
    }}
    t.textContent = msg;
    t.className = 'lia-toast show';
    clearTimeout(t._tm);
    t._tm = setTimeout(function () {{ t.className = 'lia-toast'; }}, 5000);
  }}
  function liaToastSpeech(code, jaCount) {{
    var EN = document.body.classList.contains('lang-en');
    if (code === 'not-allowed') {{
      liaToast(EN ? 'Speech blocked by browser — tap once then retry.' : '浏览器拦截了语音合成——先点一次页面再试。');
    }} else if (code === 'language-unavailable' || code === 'no-speech' || code === 'synthesis-failed') {{
      liaToast(EN
        ? 'Could not speak Japanese (voice ' + jaCount + '). Install a Japanese TTS voice, then tap the voice button to rescan.'
        : '无法朗读日语（识别到日语声线 ' + jaCount + ' 个）。请安装日语语音包后点击声线徽标重新检测。');
    }} else {{
      liaToast(EN ? 'Speech error: ' + (code || 'unknown') : '语音出错：' + (code || '未知'));
    }}
  }}
  window.kanaSpeak = function (kana, voiceURI, rate) {{
    try {{
      var text = kana;
      if (text && /^[\u3040-\u30ff]$/.test(text)) {{
        // 单假名太短，重复一次补足时长；只念假名本身——
        // 绝不拼罗马音（拉丁字母会被 TTS 按外语念，音与日语不符）
        text = text + '、' + text;
      }}
      var rt = (typeof rate === 'number' && rate > 0) ? rate : resolveTempo();
      var u = new SpeechSynthesisUtterance(text);
      u.lang = 'ja-JP';
      u.rate = rt;
      u.pitch = 1.1;
      var vs = jaVoices();
      var jaCount = vs.filter(function (vv) {{ return (vv.lang || '').replace(/_/g, '-').toLowerCase().indexOf('ja') === 0; }}).length;
      var v = resolveVoice(voiceURI) || resolveVoice(window._lastKanaVoice) || vs[0] || null;
      if (v) {{ u.voice = v; window._lastKanaVoice = v.voiceURI; }}
      else {{ liaToastSpeech('language-unavailable', jaCount); }}
      var now = Date.now();
      if (speechSynthesis.speaking && (now - (window._kanaLastClick || 0)) > 250) speechSynthesis.cancel();
      window._kanaLastClick = now;
      u.onerror = function (ev) {{
        var code = ev && ev.error;
        if (code === 'interrupted' || code === 'canceled' || code === 'request-interrupted') return;
        if (v && vs.length > 1) {{
          var fix = vs[0] !== v ? vs[0] : vs[1];
          window._lastKanaVoice = fix.voiceURI;
          var u2 = new SpeechSynthesisUtterance(text);
          u2.lang = 'ja-JP'; u2.rate = rt; u2.pitch = 1.1; u2.voice = fix;
          speechSynthesis.speak(u2);
        }}
        liaToastSpeech(code, jaCount);
      }};
      speechSynthesis.speak(u);
    }} catch (e) {{}}
  }};
  function fillKanaVoices() {{
    var boxes = document.querySelectorAll('.kana-voices');
    if (!boxes.length) return;
    var vs = jaVoices();
    fillVoicePicker(vs);
    boxes.forEach(function (box) {{
      box.innerHTML = '';
      var kana = box.getAttribute('data-h');
      vs.forEach(function (v) {{
        var b = document.createElement('button');
        b.type = 'button';
        b.className = 'voice-btn';
        b.title = v.name;
        if (window._lastKanaVoice === v.voiceURI) b.classList.add('picked');
        var m = v.name.match(/[\u4e00-\u9fff\u3040-\u30ffa-zA-Z][\u4e00-\u9fff\u3040-\u30ffa-zA-Z ]+/);
        var label = m ? m[0].replace(/ /g, '') : v.name;
        b.textContent = (window._lastKanaVoice === v.voiceURI ? '✓ ' : '') + (label.length > 12 ? label.slice(0, 12) + '\u2026' : label);
        b.addEventListener('click', function (ev) {{
          ev.stopPropagation();
          window._lastKanaVoice = v.voiceURI;
          try {{ localStorage.setItem('ls-jp-voice', v.voiceURI); }} catch (e) {{}}
          window.kanaSpeak(kana, v.voiceURI);
        }});
        box.appendChild(b);
      }});
    }});
  }}
  function ringLink(h) {{
    if (!h) return;
    document.querySelectorAll('.ring-hit').forEach(function (el) {{ el.classList.remove('ring-hit'); }});
    var sel = (window.CSS && CSS.escape) ? CSS.escape(h) : h;
    document.querySelectorAll('.kana-cell[data-h="' + sel + '"]').forEach(function (el) {{ el.classList.add('ring-hit'); }});
    document.querySelectorAll('.gloss-table tbody tr[data-h="' + sel + '"]').forEach(function (el) {{ el.classList.add('ring-hit'); }});
  }}
  window.ringLink = ringLink;

  function kmEsc(s) {{
    return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) {{
      return {{ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }}[c];
    }});
  }}
  function kmBi(zh, en) {{
    var isEn = document.body.classList.contains('lang-en');
    return kmEsc((isEn ? (en || zh) : (zh || en)) || '');
  }}
  function kmPlay(text, label) {{
    return '<button type="button" class="km-play" data-say="' + kmEsc(text) + '">'
      + '<span class="km-play-ico">&#9654;</span> ' + kmEsc(label) + '</button>';
  }}
  function kmRow(head, val) {{
    return '<span class="km-row"><b class="km-k">' + head + '</b>'
      + '<span class="km-v">' + val + '</span></span>';
  }}
  function moraSplit(s) {{
    var small = '\u3083\u3085\u3087\u3041\u3043\u3045\u3047\u3049\u308e\u30e3\u30e5\u30e7\u30a1\u30a3\u30a5\u30a7\u30a9\u30ee';
    var out = [];
    String(s || '').split('').forEach(function (ch) {{
      if (small.indexOf(ch) >= 0 && out.length) {{ out[out.length - 1] += ch; }}
      else {{ out.push(ch); }}
    }});
    return out;
  }}
  function beats(m) {{
    return '<span class="beats on" aria-hidden="true">'
      + m.map(function () {{ return '<i></i>'; }}).join('') + '</span>';
  }}
  function drawKmLines(stage) {{
    var svg = document.getElementById('km-lines');
    var center = document.getElementById('km-center');
    if (!svg || !center) return;
    var sr = stage.getBoundingClientRect();
    svg.setAttribute('width', sr.width);
    svg.setAttribute('height', sr.height);
    var c = center.getBoundingClientRect();
    var cx = c.left - sr.left + c.width / 2;
    var cy = c.top - sr.top + c.height / 2;
    var out = '';
    stage.querySelectorAll('.km-node').forEach(function (nd) {{
      var r = nd.getBoundingClientRect();
      if (!r.width) return;
      var nx = r.left - sr.left + r.width / 2;
      var ny = r.top - sr.top + r.height / 2;
      out += '<line x1="' + cx + '" y1="' + cy + '" x2="' + nx + '" y2="' + ny + '"'
        + ' stroke="rgba(201,164,101,0.55)" stroke-width="1.5" stroke-dasharray="4 4"/>';
    }});
    svg.innerHTML = out;
  }}
  window.openKanaModal = function (h) {{
    var el = document.getElementById('kana-index');
    var modal = document.getElementById('kana-modal');
    var stage = document.getElementById('km-stage');
    if (!el || !modal || !stage) return false;
    var idx = null;
    try {{ idx = JSON.parse(el.textContent); }} catch (e) {{ return false; }}
    var d = idx && idx[h];
    if (!d) return false;
    var en = document.body.classList.contains('lang-en');
    document.getElementById('km-title').textContent = (en ? 'Sound ' : '音 ') + h + (d.r ? ' · ' + d.r : '');
    document.getElementById('km-center').innerHTML =
      '<span class="km-big">' + kmEsc(h) + '</span>'
      + '<span class="km-sub">' + kmEsc(d.kat || '') + (d.r ? ' · ' + kmEsc(d.r) : '') + '</span>';
    var labels = {{ shape: ['形 · 音', 'Shape'], word: ['词 · 义', 'Word'],
                    sense: ['义 · 文', 'Sense'], root: ['源 · 字', 'Root'],
                    law: ['律 · 调', 'Law'] }};
    var mseq = moraSplit(d.kana || h);
    var sat = {{
      shape: kmRow(kmBi('假名', 'kana'), kmEsc(d.kat || ''))
             + kmRow(kmBi('罗马音', 'romaji'), kmEsc(d.r || ''))
             + (d.note_zh || d.note_en ? kmRow(kmBi('发音', 'pron.'), kmBi(d.note_zh, d.note_en)) : '')
             + kmPlay(h, en ? 'sound' : '读此音'),
      word: kmRow(kmBi('語', 'word'), kmEsc(d.kanji || '') + ' ' + kmEsc(d.kana || '')
              + (d.rom ? ' <i>' + kmEsc(d.rom) + '</i>' : ''))
            + kmRow(kmBi('義', 'meaning'), kmBi(d.meaning_zh, d.meaning_en))
            + (d.kana ? kmPlay(d.kana, en ? 'word' : '读词') : ''),
      sense: kmRow(kmBi('季語', 'season'), kmBi(d.sea_zh, d.sea_en))
             + kmRow(kmBi('美学', 'art'), kmBi(d.art_zh, d.art_en))
             + kmRow(kmBi('典故', 'ref'), kmBi(d.ref_zh, d.ref_en)),
      root: kmRow(kmBi('字源', 'origin'), kmEsc(d.origin || '') + (d.origin_k ? ' · ' + kmEsc(d.origin_k) : ''))
            + kmRow(kmBi('分层', 'layer'), kmBi(d.layer_zh, d.layer_en)),
      law: kmRow(kmBi('拍 / morae', 'morae'), kmEsc(String(mseq.length)) + beats(mseq))
            + kmRow(kmBi('读法', 'reading'), kmEsc(d.kana || h))
            + '<a class="km-link" href="#ring-law">' + kmBi('第五旋 · 律 · 音调四型 →', 'Ring 5 · Law · four pitch types →') + '</a>'
            + ' <a class="ojad-link" target="_blank" rel="noopener" href="https://www.gavo.t.u-tokyo.ac.jp/ojad/search/index/word:'
            + encodeURIComponent(d.kana || h) + '">' + kmBi('OJAD 声调', 'OJAD accent') + '</a>'
            + (d.kana ? kmPlay(d.kana, en ? 'word' : '读词') : '')
    }};
    ['shape', 'word', 'sense', 'root', 'law'].forEach(function (k) {{
      var box = stage.querySelector('[data-sat="' + k + '"]');
      if (!box) return;
      box.innerHTML = '<div class="km-node-h">' + kmEsc(en ? labels[k][1] : labels[k][0]) + '</div>' + sat[k];
    }});
    var layer = kmBi(d.layer_zh, d.layer_en);
    document.getElementById('km-sent').innerHTML =
      (layer ? '<span class="lyr-badge">' + layer + '</span>' : '')
      + '<div class="km-sent-ja"><span lang="ja">' + kmEsc(d.sent || '') + '</span>'
      + (d.sent_rom ? '<span class="rom">' + kmEsc(d.sent_rom) + '</span>' : '') + '</div>'
      + '<div class="km-sent-tr">' + kmBi(d.tr_zh, d.tr_en) + '</div>'
      + (d.sent ? kmPlay(d.sent, en ? 'sentence' : '读整句') : '');
    modal.hidden = false;
    document.body.classList.add('modal-open');
    drawKmLines(stage);
    return true;
  }};
  window.closeKanaModal = function () {{
    var m = document.getElementById('kana-modal');
    if (!m) return;
    m.hidden = true;
    document.body.classList.remove('modal-open');
    try {{ speechSynthesis.cancel(); }} catch (e) {{}}
  }};
  var kanaModal = document.getElementById('kana-modal');
  if (kanaModal) {{
    kanaModal.addEventListener('click', function (ev) {{
      if (ev.target.closest && ev.target.closest('[data-km-close]')) {{ window.closeKanaModal(); return; }}
      var p = ev.target.closest && ev.target.closest('.km-play');
      if (p) {{ ev.stopPropagation(); window.kanaSpeak(p.getAttribute('data-say')); }}
    }});
  }}
  document.querySelectorAll('.word-play').forEach(function (b) {{
    b.addEventListener('click', function (ev) {{
      ev.stopPropagation();
      var r = parseFloat(b.getAttribute('data-rate') || '');
      window.kanaSpeak(b.getAttribute('data-say'), null, isFinite(r) ? r : undefined);
    }});
  }});
  document.querySelectorAll('.mm-leaf[data-h]').forEach(function (b) {{
    b.addEventListener('click', function (ev) {{
      ev.stopPropagation();
      var h = b.getAttribute('data-h');
      ringLink(h);
      window.openKanaModal(h);
    }});
  }});
  var mmR = document.getElementById('mm-reverse');
  if (mmR) mmR.addEventListener('click', function () {{
    document.body.classList.toggle('mm-reverse');
    mmR.classList.toggle('on');
  }});
  var mmB = document.getElementById('mm-beats');
  if (mmB) mmB.addEventListener('click', function () {{
    document.body.classList.toggle('show-beats');
    mmB.classList.toggle('on');
  }});
  window.addEventListener('resize', function () {{
    var m = document.getElementById('kana-modal');
    var s = document.getElementById('km-stage');
    if (m && !m.hidden && s) drawKmLines(s);
  }});
  document.addEventListener('click', function (ev) {{
    if (document.body.classList.contains('modal-open')) return;
    if (ev.target.closest && ev.target.closest('.voice-btn')) return;
    var hit = null;
    if (ev.target.closest) {{
      hit = ev.target.closest('.kana-cell[data-h]');
      if (!hit) {{
        var row = ev.target.closest('.gloss-table tbody tr[data-h]');
        if (row) hit = row;
      }}
    }}
    if (!hit) return;
    var h = hit.getAttribute('data-h');
    var big = hit.querySelector ? hit.querySelector('.big') : null;
    if (big) h = big.textContent.trim();
    ringLink(h);
    window.openKanaModal(h);
  }});
  document.querySelectorAll('.spiral-pills .pill').forEach(function (a) {{
    a.addEventListener('click', function () {{
      var id = (a.getAttribute('href') || '').replace('#', '');
      var target = document.getElementById(id);
      if (!target) return;
      var on = target.classList.contains('ring-focus');
      document.querySelectorAll('.spiral-ring').forEach(function (r) {{ r.classList.remove('ring-focus'); }});
      document.querySelectorAll('.spiral-pills .pill').forEach(function (p) {{ p.classList.remove('on'); }});
      if (!on) {{
        target.classList.add('ring-focus');
        a.classList.add('on');
        window.setTimeout(function () {{ target.scrollIntoView({{ behavior: 'smooth', block: 'start' }}); }}, 30);
      }}
    }});
  }});
  document.addEventListener('keydown', function (ev) {{
    if (ev.key === 'Escape') {{
      if (document.body.classList.contains('modal-open') && window.closeKanaModal) {{ window.closeKanaModal(); return; }}
      document.querySelectorAll('.spiral-ring').forEach(function (r) {{ r.classList.remove('ring-focus'); }});
      document.querySelectorAll('.spiral-pills .pill').forEach(function (p) {{ p.classList.remove('on'); }});
    }}
  }});
  document.querySelectorAll('.layer-bar .lyr-btn').forEach(function (b) {{
    b.addEventListener('click', function () {{
      var want = b.getAttribute('data-layer');
      document.querySelectorAll('.layer-bar .lyr-btn').forEach(function (x) {{
        x.classList.toggle('on', x.getAttribute('data-layer') === want);
      }});
      document.querySelectorAll('.gloss-table tbody tr[data-layer]').forEach(function (tr) {{
        var L = tr.getAttribute('data-layer');
        tr.classList.toggle('layer-off', !!want && L !== want);
      }});
    }});
  }});
  if ('speechSynthesis' in window) {{
    rescanVoices(false);
    try {{
      speechSynthesis.onvoiceschanged = function () {{
        rescanVoices(false);
      }};
    }} catch (e) {{}}
  }}
}})();
</script>
</body>
</html>
"""


# ── 工具 ───────────────────────────────────────────────────────
def e(s):
    return html.escape(str(s), quote=True)


def read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def parse_frontmatter(text):
    """顶部 ---json ... --- frontmatter → (dict|None, body)"""
    m = re.match(r"^---json\s*\n(.*?)\n---\s*\n?", text, re.S)
    if not m:
        return None, text
    return json.loads(m.group(1)), text[m.end():]


def strip_h1(md):
    """去掉第一个 '# ' 标题行(页面体现为 hero, 不重复占 h1)"""
    return re.sub(r"^# .*\n+", "", md, count=1)


def render_prose(md_body):
    """多段双语 markdown → HTML。无标记段 = 共享段（zh/en 双份）。"""
    pattern = re.compile(r"^\s*<!--\s*(zh|en)\s*-->\s*$", re.M)
    parts = pattern.split(md_body)
    out = []
    if parts[0].strip():
        h = _render_md(parts[0])
        out.append(f'<div data-both="1"><div data-bit="zh">{h}</div><div data-bit="en">{h}</div></div>')
    for i in range(1, len(parts), 2):
        bit, chunk = parts[i], parts[i + 1]
        if not chunk.strip():
            continue
        out.append(f'<div data-both="1"><div data-bit="{bit}">{_render_md(chunk)}</div></div>')
    return "".join(out)


def _render_md(md_text):
    MD.reset()
    return MD.convert(md_text).strip()


def zh_en(text_zh, text_en):
    return f'<span data-zh>{e(text_zh)}</span><span data-en>{e(text_en)}</span>'


# ── 组件 ───────────────────────────────────────────────────────
def crumbs(*segments):
    """(label, href|None, label, href|None, ...) 扁平行参 → 面包屑 HTML，以 › 分隔"""
    parts = []
    for i in range(0, len(segments) - 1, 2):
        label, href = segments[i], segments[i + 1]
        if href:
            parts.append(f'<a href="{e(href)}">{e(label)}</a>')
        else:
            parts.append(f"<span>{e(label)}</span>")
    return " &rsaquo; ".join(parts)


def hero(crumb, h1_zh, h1_en, sub_zh, sub_en):
    return (
        '<section class="learn-hero">'
        f"<p class=\"crumb\">{crumb}</p>"
        f'<h1>{e(h1_zh)}</h1>'
        f'<p class="sub">{e(sub_zh)} &middot; {e(sub_en)}</p>'
        "</section>"
    )


def lcard(lang):
    ready = lang.get("status") == "active"
    stat = "ready" if ready else "planned"
    stat_zh, stat_en = ("学习入口" if ready else "建设中"), ("Enter" if ready else "Planned")
    glyph = f'<span class="glyph">{e(lang["glyph"])}</span>'
    name_zh = f'<span class="name" data-zh>{e(lang["name_zh"])}</span>'
    name_en = f'<span class="name" data-en>{e(lang["name_en"])}</span>'
    summary = (f'<span class="summary" data-zh>{e(lang["summary_zh"])}</span>'
               f'<span class="summary" data-en>{e(lang["summary_en"])}</span>')
    stat_tag = (f'<span class="status {stat}" data-zh>{stat_zh}</span>'
                f'<span class="status {stat}" data-en>{stat_en}</span>')
    enter = "" if not ready else (
        f'<a class="enter" href="{e(lang["href"])}" data-zh>进入学习 &rarr;</a>'
        f'<a class="enter" href="{e(lang["href"])}" data-en>Enter &rarr;</a>'
    )
    href = e(lang["href"]) if ready else "#future"
    return (f'<a class="card card-{stat}" href="{href}">{glyph}{name_zh}{name_en}<br>'
            f'<span class="iso">{e(lang["iso"])}</span>{summary}{stat_tag}{enter}</a>')


def render_hub_cards(registry, prose):
    langs = registry["languages"]
    active = [x for x in langs if x.get("status") == "active"]
    planned = [x for x in langs if x.get("status") != "active"]
    cards = "".join(lcard(x) for x in active + planned)
    return prose + f'<section class="cards" aria-label="languages">{cards}</section>'


def mcard(module):
    ready = module.get("status") == "ready"
    body = (
        f'<span class="name" data-zh>{e(module["name_zh"])}</span>'
        f'<span class="name" data-en>{e(module["name_en"])}</span><br>'
        f'<span class="summary" data-zh>{e(module["desc_zh"])}</span>'
        f'<span class="summary" data-en>{e(module["desc_en"])}</span>'
        f'<span class="status {"ready" if ready else "planned"}" data-zh>{"可学" if ready else "筹备中"}</span>'
        f'<span class="status {"ready" if ready else "planned"}" data-en>{"Ready" if ready else "Coming"}</span>'
    )
    if ready:
        return f'<a class="card card-ready" href="{e(module["href"])}">{body}</a>'
    return f'<span class="card card-planned" aria-disabled="true">{body}</span>'


def module_grid(modules):
    return f'<section class="cards" aria-label="modules" style="max-width:820px">{"".join(mcard(m) for m in modules)}</section>'


def kana_origin_line(c):
    """tooltip 内的字源行（第四旋·源 在每一格上留下的回望线索）。"""
    if not (c.get("origin") or c.get("origin_k")):
        return ""
    o = e(c.get("origin", ""))
    ok = e(c.get("origin_k", ""))
    return (f'<span class="kana-origin"><span data-zh>字源 {o} / {ok}</span>'
            f'<span data-en>origin {o} / {ok}</span></span>')


def kana_table_html(data):
    chart = data["chart"]
    hdr = "<th></th>" + "".join(
        f'<th class="vowel">{e(col[0])}<span class="r">{e(col[1])}</span></th>'
        for col in chart["columns"]
    )
    rows = []
    for row in chart["rows"]:
        cells = []
        for c in row["cells"]:
            if c.get("void"):
                cells.append('<td class="kana-cell void"><span>&mdash;</span></td>')
                continue
            cls = "kana-cell" + (" particle" if c.get("particle") else "")
            tip = ""
            note_zh = c.get("note_zh", "")
            note_en = c.get("note_en", "")
            if note_zh or note_en or c.get("origin") or c.get("origin_k"):
                tip = (
                    f'<span class="kana-tip">'
                    f'<span data-zh>{e(note_zh)}</span>'
                    f'<span data-en>{e(note_en)}</span>'
                    f'{kana_origin_line(c)}'
                    f'<span class="kana-voices" data-h="{e(c["h"])}" data-r="{e(c["r"])}"></span>'
                    f'</span>'
                )
            cells.append(
                f'<td class="{cls}" onclick="kanaSpeak(\'{e(c["h"])}\')" data-h="{e(c["h"])}" data-r="{e(c["r"])}">'
                f'<span class="kat">{e(c["kat"])}</span>'
                f'<span class="h">{e(c["h"])}</span>'
                f'<span class="r">{e(c["r"])}</span>'
                f'{tip}'
                f"</td>"
            )
        roma = row["cells"][0].get("r", "")[:1]
        rows.append(
            f'<tr><td class="rowname">{e(row["row"])}<span class="r">{e(roma)}</span></td>'
            f'{"".join(cells)}</tr>'
        )
    n = chart["n"]
    ntip = ""
    if n.get("note_zh") or n.get("note_en") or n.get("origin") or n.get("origin_k"):
        ntip = (
            f'<span class="kana-tip">'
            f'<span data-zh>{e(n.get("note_zh", ""))}</span>'
            f'<span data-en>{e(n.get("note_en", ""))}</span>'
            f'{kana_origin_line(n)}'
            f'<span class="kana-voices" data-h="{e(n["h"])}" data-r="{e(n["r"])}"></span>'
            f'</span>'
        )
    rows.append(
        f'<tr><td class="rowname">{e(n["h"])}<span class="r">{e(n["r"])}</span></td>'
        f'<td colspan="5" class="kana-cell" onclick="kanaSpeak(\'{e(n["h"])}\')" data-h="{e(n["h"])}" data-r="{e(n["r"])}">'
        f'<span class="kat">{e(n["kat"])}</span><span class="h">{e(n["h"])}</span><span class="r">{e(n["r"])}</span>'
        f'{ntip}'
        f"</td></tr>"
    )
    notes = chart.get("notes", {})
    zh_notes = " ".join(filter(None, [notes.get("void_zh"), notes.get("particle_zh")]))
    en_notes = " ".join(filter(None, [notes.get("void_en"), notes.get("particle_en")]))
    return (
        "<div class='kana-wrap'>"
        f"<table class='kana-table'><thead><tr>{hdr}</tr></thead><tbody>{''.join(rows)}</tbody></table>"
        + (f'<div class="kana-notes" data-zh>{e(zh_notes)}</div>' if zh_notes else "")
        + (f'<div class="kana-notes" data-en>{e(en_notes)}</div>' if en_notes else "")
        + '</div>'
    )


def derived_html(data):
    chips = []
    for d in data["derived"]:
        note_zh = f'<span class="dnote" data-zh>{e(d["note_zh"])}</span>' if d.get("note_zh") else ""
        note_en = f'<span class="dnote" data-en>{e(d["note_en"])}</span>' if d.get("note_en") else ""
        chips.append(
            f'<span>'
            f'<b class="dl" data-zh>{e(d["name_zh"])}</b>'
            f'<b class="dl" data-en>{e(d["name_en"])}</b>'
            f'<span class="dname">{e(d["kana"])}</span>{note_zh}{note_en}'
            f"</span>"
        )
    return f'<div class="derived">{"".join(chips)}</div>'


def vocab_html(data):
    rows = []
    for v in data["vocab"]:
         rows.append(
             f'<tr data-h="{e(v["h"])}" data-layer="{e(v.get("layer_zh", ""))}">'
             f'<td class="kc"><span class="big">{e(v["h"])}</span>'
             f'<span class="kat">{e(v["kat"])}</span>'
             f'<span class="rom">{e(v["r"])}</span>{beats_html(v["kana"])}</td>'
             f'<td><span class="kw2">{e(v["kanji"])}</span> '
             f'<span class="furigana">{e(v["kana"])}</span>'
             f'<span class="rom">{e(v["rom"])}</span>'
             f'<button type="button" class="word-play" data-say="{e(v["kana"])}" title="读词 / speak word">&#9654;</button>'
             f'{ojad_link(v["kana"])}<br>'
             f'<span class="min-tr" data-zh>{e(v["meaning_zh"])}</span>'
             f'<span class="min-tr" data-en>{e(v["meaning_en"])}</span></td>'
             f'<td class="lyr"><span class="lyr-badge" data-zh>{e(v.get("layer_zh", ""))}</span>'
             f'<span class="lyr-badge" data-en>{e(v.get("layer_en", ""))}</span></td>'
             f'<td class="sent"><span lang="ja">{e(v["sent"])}</span>'
             f'<span class="rom">{e(v["sent_rom"])}</span>'
             f'<span class="tr" data-zh>{e(v["tr_zh"])}</span>'
             f'<span class="tr" data-en>{e(v["tr_en"])}</span>'
             f'<span class="kana-voices sent-voices" data-h="{e(v["sent"])}" data-r="{e(v["sent_rom"])}"></span></td>'
             "</tr>"
         )
    layers = []
    for v in data["vocab"]:
        L = v.get("layer_zh", "")
        if L and L not in layers:
            layers.append(L)
    bar = ('<div class="layer-bar" role="toolbar" aria-label="layer filter">'
           '<button type="button" class="lyr-btn on" data-layer="">全部 all</button>'
           + "".join(f'<button type="button" class="lyr-btn" data-layer="{e(L)}">{e(L)}</button>' for L in layers)
           + "</div>")
    return (
        bar +
        '<div class="gloss-wrap"><table class="gloss-table"><thead><tr>'
        "<th>音</th><th>語</th><th>分层 / Layer</th><th>例句 / Example</th>"
        "</tr></thead><tbody>"
        + "".join(rows)
        + "</tbody></table></div>"
    )


# ── 第五旋·律：拍切分 / 声调 / 媒体（数据驱动，逐词音调不臆断）──
_MORA_SMALL = set("ゃゅょぁぃぅぇぉゎャュョァィゥェォヮ")
_RING_LABEL = {"shape": "形 Shape", "word": "词 Word", "sense": "义 Sense",
               "root": "源 Origin", "law": "律 Law"}


def mora_split(s):
    """假名串切分为拍（拗音合一拍；っ/ー/ん 各占一拍）。"""
    out = []
    for ch in (s or ""):
        if ch in _MORA_SMALL and out:
            out[-1] += ch
        else:
            out.append(ch)
    return out


def beats_html(s, cap=10, always=False):
    m = mora_split(s)
    if not m or len(m) > cap:
        return ""
    cls = "beats on" if always else "beats"
    return f'<span class="{cls}" aria-hidden="true">' + "".join("<i></i>" for _ in m) + "</span>"


OJAD_SEARCH = "https://www.gavo.t.u-tokyo.ac.jp/ojad/search/index/word:"


def ojad_link(kana, label="調", cls="ojad-link"):
    """指向 OJAD 该词的声调查询页（把「以 OJAD 为准」变成可点核验）。"""
    if not kana:
        return ""
    u = OJAD_SEARCH + urllib.parse.quote(kana, safe="")
    return (f'<a class="{cls}" href="{u}" target="_blank" rel="noopener" '
            f'title="OJAD 声调核验 / accent lookup">{label}</a>')


def pitch_svg(seq, w=148, h=56):
    """四型高低调示意图（自绘 SVG，离线可用）。seq 如 'LHHL'。"""
    hi, lo = 15, 41
    n = max(len(seq), 2)
    step = (w - 16) / (n - 1)
    pts = [(round(8 + i * step, 1), hi if c == "H" else lo) for i, c in enumerate(seq)]
    poly = " ".join(f"{x},{y}" for x, y in pts)
    dots = "".join(f'<circle cx="{x}" cy="{y}" r="3.1"/>' for x, y in pts)
    marks = ""
    for i in range(1, len(seq)):
        if seq[i - 1] == "H" and seq[i] == "L":
            mx = (pts[i - 1][0] + pts[i][0]) / 2
            marks += (f'<line x1="{mx}" y1="{hi}" x2="{mx}" y2="{lo}" '
                      'stroke="#c0705f" stroke-width="1.3" stroke-dasharray="3 3"/>')
    return (f'<svg class="pitch-svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" '
            'role="img" aria-hidden="true">'
            f'<polyline points="{poly}" fill="none" stroke="#C9A465" stroke-width="2.3" '
            'stroke-linecap="round" stroke-linejoin="round"/>'
            f'{marks}<g fill="#8a6f3d">{dots}</g></svg>')


def retro_html(sid, data):
    """回首内观：每旋的「回望上一旋」面板。"""
    b = (data.get("backrefs") or {}).get(sid)
    if not b or not b.get("back"):
        return ""  # 无上一旋可回望者（如 shape 的回望即在收束，不在此处）
    back = b["back"]
    jump = f'<a class="retro-jump" href="#ring-{e(back)}">&uarr; {e(_RING_LABEL.get(back, back))}</a>'
    return ('<aside class="retro"><span class="retro-tag"><span data-zh>回首内观</span>'
            '<span data-en>look back</span></span>'
            f'<p data-zh>{e(b.get("zh", ""))}</p><p data-en>{e(b.get("en", ""))}</p>'
            f'{jump}</aside>')


def prosody_html(data):
    """第五旋·律：拍/节奏 + 特殊拍 + 声调四型 + 最小对立对 + 无声化。"""
    p = data.get("prosody") or {}
    if not p:
        return ""
    parts = []
    m = p.get("mora") or {}
    if m:
        exs = []
        for key in ("ex", "ex2"):
            x = m.get(key) or {}
            if not x:
                continue
            bts = beats_html(x.get("kana", ""), always=True)
            temps = "".join(
                f'<button type="button" class="word-play tempo" data-say="{e(x.get("kana", ""))}" '
                f'data-rate="{r}" title="{t}">&#9654;{t}</button>'
                for r, t in ((0.7, "慢"), (1.0, "中"), (1.4, "快")))
            exs.append(
                f'<div class="pr-ex"><span class="pr-kana" lang="ja">{e(x.get("kana", ""))}</span>'
                f'<span class="pr-rom">{e(x.get("rom", ""))}</span>'
                f'{bts}{ojad_link(x.get("kana", ""))}'
                f'<span class="pr-cap" data-zh>{e(x.get("zh", ""))}</span>'
                f'<span class="pr-cap" data-en>{e(x.get("en", ""))}</span>'
                f'<span class="pr-tempo">{temps}</span></div>')
        parts.append(
            '<div class="pr-block"><h4 class="pr-h"><span data-zh>拍 · 节奏</span>'
            '<span data-en>Mora · rhythm</span></h4>'
            f'<p class="pr-p" data-zh>{e(m.get("zh", ""))}</p>'
            f'<p class="pr-p" data-en>{e(m.get("en", ""))}</p>'
            f'<div class="pr-exs">{"".join(exs)}</div></div>')
    sp = p.get("special") or []
    if sp:
        rows = "".join(
            f'<tr><td class="pr-k" lang="ja">{e(s.get("k", ""))}</td>'
            f'<td><span data-zh>{e(s.get("zh", ""))}</span>'
            f'<span data-en>{e(s.get("zh", ""))}</span></td>'
            f'<td><span data-zh>{e(s.get("note_zh", ""))}</span>'
            f'<span data-en>{e(s.get("note_en", ""))}</span></td></tr>' for s in sp)
        parts.append(
            '<div class="pr-block"><h4 class="pr-h"><span data-zh>特殊拍</span>'
            '<span data-en>Special morae</span></h4>'
            '<div class="gloss-wrap"><table class="gloss-table pr-table"><thead><tr>'
            '<th>拍</th><th>名</th><th>说明 / note</th></tr></thead><tbody>'
            f'{rows}</tbody></table></div></div>')
    ai = p.get("accent_intro") or {}
    at = p.get("accent_types") or []
    if at:
        cards = "".join(
            f'<figure class="pitch-card">{pitch_svg(t.get("seq", "LHHH"))}'
            f'<figcaption><b>{e(t.get("name_zh", ""))}</b>'
            f'<span class="pc-en">{e(t.get("name_en", ""))}</span>'
            f'<span class="pc-num">{e(str(t.get("num", "")))}</span>'
            f'<span class="pc-d" data-zh>{e(t.get("zh", ""))}</span>'
            f'<span class="pc-d" data-en>{e(t.get("en", ""))}</span></figcaption></figure>'
            for t in at)
        parts.append(
            '<div class="pr-block" id="pitch"><h4 class="pr-h"><span data-zh>音调 · 高低</span>'
            '<span data-en>Pitch accent</span></h4>'
            f'<p class="pr-p" data-zh>{e(ai.get("zh", ""))}</p>'
            f'<p class="pr-p" data-en>{e(ai.get("en", ""))}</p>'
            f'<div class="pitch-grid">{cards}</div>'
            f'<p class="pr-note" data-zh>{e(ai.get("note_zh", ""))}</p>'
            f'<p class="pr-note" data-en>{e(ai.get("note_en", ""))}</p></div>')
    mp = p.get("minimal_pairs") or []
    if mp:
        def _mp_cell(o):
            if not o:
                return ""
            return (f'<span class="mp-kana" lang="ja">{e(o.get("kana", ""))}</span>'
                    f'{beats_html(o.get("kana", ""), always=True)}'
                    f'<span class="mp-rom">{e(o.get("rom", ""))}</span>'
                    f'<span class="mp-m" data-zh>{e(o.get("zh", ""))}</span>'
                    f'<span class="mp-m" data-en>{e(o.get("en", ""))}</span>'
                    f'<button type="button" class="word-play" data-say="{e(o.get("kana", ""))}">&#9654;</button>'
                    f'{ojad_link(o.get("kana", ""))}')
        rows = []
        for pair in mp:
            sides = (f'<div class="mp-side">{_mp_cell(pair.get("a"))}</div>'
                     f'<div class="mp-side">{_mp_cell(pair.get("b"))}</div>')
            if pair.get("c"):
                sides += f'<div class="mp-side">{_mp_cell(pair.get("c"))}</div>'
            src = (f' <a class="mp-src" href="{e(pair["src"])}" target="_blank" rel="noopener">src</a>'
                   if pair.get("src") else "")
            rows.append(
                f'<div class="mp-row" data-kind="{e(pair.get("kind", ""))}">'
                f'<div class="mp-sides">{sides}</div>'
                f'<div class="mp-why"><span data-zh>{e(pair.get("zh", ""))}</span>'
                f'<span data-en>{e(pair.get("en", ""))}</span>{src}</div></div>')
        parts.append(
            '<div class="pr-block"><h4 class="pr-h"><span data-zh>最小对立对</span>'
            '<span data-en>Minimal pairs</span></h4>'
            f'<div class="mp-wrap">{"".join(rows)}</div></div>')
    dv = p.get("devoicing") or {}
    if dv:
        parts.append(
            '<div class="pr-block"><h4 class="pr-h"><span data-zh>无声化</span>'
            '<span data-en>Devoicing</span></h4>'
            f'<p class="pr-p" data-zh>{e(dv.get("zh", ""))}</p>'
            f'<p class="pr-p" data-en>{e(dv.get("en", ""))}</p></div>')
    return f'<div class="prosody">{"".join(parts)}</div>'


def media_html(data):
    """律旋附：笔顺图 + 声调视频 + 拓展阅读（外链均已核实）。"""
    md = data.get("media") or {}
    if not md:
        return ""
    blocks = []
    img = md.get("image") or {}
    if img:
        blocks.append(
            '<figure class="media-fig">'
            f'<img loading="lazy" alt="kana stroke order" src="{e(img.get("url", ""))}" '
            "onerror=\"this.style.display='none';this.parentNode.classList.add('img-fail')\">"
            f'<figcaption><span data-zh>{e(img.get("cap_zh", ""))}</span>'
            f'<span data-en>{e(img.get("cap_en", ""))}</span>'
            f'<a class="media-credit" href="{e(img.get("page", ""))}" target="_blank" rel="noopener">{e(img.get("credit", ""))}</a>'
            '</figcaption></figure>')
    vid = md.get("video") or {}
    if vid:
        blocks.append(
            '<figure class="media-vid">'
            f'<div class="vid-frame"><iframe loading="lazy" '
            f'src="https://www.youtube-nocookie.com/embed/{e(vid.get("id", ""))}" '
            'title="pitch accent" allow="accelerometer; clipboard-write; encrypted-media; '
            'gyroscope; picture-in-picture" allowfullscreen></iframe></div>'
            f'<figcaption><span data-zh>{e(vid.get("title_zh", ""))}</span>'
            f'<span data-en>{e(vid.get("title_en", ""))}</span>'
            f'<span class="media-note" data-zh>{e(vid.get("note_zh", ""))}</span>'
            f'<span class="media-note" data-en>{e(vid.get("note_en", ""))}</span>'
            f' · <a href="{e(vid.get("url", ""))}" target="_blank" rel="noopener">YouTube</a>'
            '</figcaption></figure>')
    rd = md.get("read") or []
    if rd:
        cards = "".join(
            f'<a class="read-card" href="{e(r.get("url", ""))}" target="_blank" rel="noopener">'
            f'<b data-zh>{e(r.get("zh", ""))}</b><b data-en>{e(r.get("en", ""))}</b>'
            f'<span data-zh>{e(r.get("note_zh", ""))}</span>'
            f'<span data-en>{e(r.get("note_en", ""))}</span></a>' for r in rd)
        blocks.append(f'<div class="read-grid">{cards}</div>')
    return ('<div class="pr-block media-block"><h4 class="pr-h"><span data-zh>图 · 影 · 拓展</span>'
            '<span data-en>Images · video · further</span></h4>'
            + "".join(blocks) + '</div>')


def mindmap_html(data):
    """螺旋导图：主干(五旋) + 枝(要点) + 叶(46音/词)；可逆走、可折叠、可生长。"""
    s = data.get("spiral") or {}
    layers = s.get("layers") or []
    chart = data.get("chart") or {}
    cells = [c for row in chart.get("rows", []) for c in row.get("cells", []) if not c.get("void")]
    n = chart.get("n")
    if isinstance(n, dict):
        cells.append(n)
    vocab = data.get("vocab") or []
    leaves = {
        "shape": [(c["h"], c["h"], c.get("r", "")) for c in cells],
        "word": [(v["h"], v.get("kanji") or v["h"], v.get("meaning_zh", "")) for v in vocab],
        "sense": [(v["h"], (v.get("sea_zh") or v["h"])[:6], v.get("meaning_zh", "")) for v in vocab],
        "root": [(c["h"], c.get("origin") or c["h"], c.get("note_zh", "")) for c in cells],
    }
    npair = len((data.get("prosody") or {}).get("minimal_pairs") or [])
    rings = []
    for i, l in enumerate(layers, 1):
        sid = l.get("id", "")
        pv = [x.strip() for x in (l.get("promise_zh", "") or "").replace(" · ", "|").split("|")]
        chips = "".join(f'<span class="mm-chip">{e(x)}</span>' for x in pv if x)
        lv = leaves.get(sid)
        if lv:
            inner = "".join(
                f'<button type="button" class="mm-leaf" data-h="{e(h)}" title="{e(t)}">{e(disp)}</button>'
                for h, disp, t in lv)
            det = (f'<details class="mm-det"><summary><span data-zh>叶 · {len(lv)}</span>'
                   f'<span data-en>leaves · {len(lv)}</span></summary>'
                   f'<div class="mm-leaves">{inner}</div></details>')
        else:
            det = ('<div class="mm-leaves mm-leaves-law">'
                   '<a class="mm-leaf" href="#pitch" data-zh>音调 4 型</a>'
                   '<a class="mm-leaf" href="#pitch" data-en>4 pitch types</a>'
                   f'<a class="mm-leaf" href="#ring-law"><span data-zh>最小对立对 {npair}</span>'
                   f'<span data-en>minimal pairs {npair}</span></a></div>')
        rings.append(
            f'<li class="mm-ring" data-ring="{e(sid)}">'
            f'<a class="mm-trunk" href="#ring-{e(sid)}"><b>{i}</b>'
            f'<span class="mm-name" data-zh>{e(l.get("zh", ""))}</span>'
            f'<span class="mm-name" data-en>{e(l.get("en", ""))}</span>'
            f'<span class="mm-title" data-zh>{e(l.get("title_zh", ""))}</span>'
            f'<span class="mm-title" data-en>{e(l.get("title_en", ""))}</span></a>'
            f'<div class="mm-branch">{chips}</div>{det}</li>')
    return (
        '<section class="mindmap" id="mindmap">'
        '<div class="mm-head"><h3 class="mm-h"><span data-zh>螺旋导图 · 主干与枝叶</span>'
        '<span data-en>Spiral map · trunk and leaves</span></h3>'
        '<div class="mm-ctrl">'
        '<button type="button" class="mm-btn" id="mm-reverse"><span data-zh>逆走 ⇅ 从终回望</span>'
        '<span data-en>reverse ⇅ from the end</span></button>'
        '<button type="button" class="mm-btn" id="mm-beats"><span data-zh>拍点 · 叠加</span>'
        '<span data-en>beats · overlay</span></button>'
        '</div></div>'
        '<div class="mm-tree"><div class="mm-root"><b>五十音</b><span>gojūon</span></div>'
        f'<ul class="mm-rings">{"".join(rings)}</ul></div>'
        '<p class="mm-note" data-zh>主干 = 五旋；枝 = 各旋要点；叶 = 46 音与词。知识库长一分，此图即长一枝——向外生长，也向内回望。</p>'
        '<p class="mm-note" data-en>Trunk = five rings; branches = key ideas; leaves = the 46 sounds and words. As the knowledge base grows, so grows this map — outward and inward.</p>'
        '</section>')


# ── 四旋螺环（spiral·同芯回望）──────────────────────────────
def spiral_guide_html(data):
    """旋导：tale + 四旋达 / 回到第一旋的提示（顶部导航）。"""
    s = data.get("spiral") or {}
    layers = s.get("layers") or []
    pills = []
    for i, l in enumerate(layers, 1):
        pills.append(
            f'<a class="pill" href="#ring-{e(l.get("id", ""))}">'
            f'<b>{i}</b>'
            f'<span class="pz" data-zh>{e(l.get("zh", ""))}</span>'
            f'<span class="pz" data-en>{e(l.get("en", ""))}</span>'
            f'<span class="pt" data-zh>{e(l.get("title_zh", ""))}</span>'
            f'<span class="pt" data-en>{e(l.get("title_en", ""))}</span>'
            f'<span class="pp" data-zh>{e(l.get("promise_zh", ""))}</span>'
            f'<span class="pp" data-en>{e(l.get("promise_en", ""))}</span></a>'
        )
    tale = (f'<p class="spiral-tale" data-zh>{e(s.get("tale_zh", ""))}</p>'
            f'<p class="spiral-tale" data-en>{e(s.get("tale_en", ""))}</p>')
    return (f'<section class="spiral-guide" id="spiral-top">'
            f'<h2 class="ring-h"><span class="ring-tag">旋 · Spiral</span>'
            f'<span data-zh>同一张表，四圈深意</span><span data-en>one chart, four rings deep</span></h2>'
            f'{tale}'
            f'<nav class="spiral-pills">{"".join(pills)}</nav>'
            f'<p class="spiral-hint" data-zh>学到第五旋，回到第一旋——同一个音会露出新的深度。</p>'
            f'<p class="spiral-hint" data-en>Finish ring five, return to ring one — the same sound is deeper now.</p>'
            f'{mindmap_html(data)}'
            f'</section>')


def cultural_html(data):
    """第三旋·义：季语（岁时）/ 美学一言 / 文化典故 坐标表。"""
    rows = []
    for v in data["vocab"]:
        rows.append(
             '<tr data-h="' + e(v["h"]) + '" data-layer="' + e(v.get("layer_zh", "")) + '">'
             f'<td class="kc"><span class="big">{e(v["h"])}</span>'
             f'<span class="kat">{e(v["kat"])}</span>'
             f'<span class="rom">{e(v["r"])}</span>{beats_html(v["kana"])}</td>'
             f'<td><span class="kw2">{e(v["kanji"])}</span> '
             f'<span class="furigana">{e(v["kana"])}</span>'
             f'<span class="rom">{e(v["rom"])}</span>'
             f'<button type="button" class="word-play" data-say="{e(v["kana"])}" title="读词 / speak word">&#9654;</button>'
             f'{ojad_link(v["kana"])}<br>'
             f'<span class="min-tr" data-zh>{e(v["meaning_zh"])}</span>'
             f'<span class="min-tr" data-en>{e(v["meaning_en"])}</span></td>'
             f'<td class="lyr"><span class="lyr-badge" data-zh>{e(v.get("layer_zh", ""))}</span>'
             f'<span class="lyr-badge" data-en>{e(v.get("layer_en", ""))}</span></td>'
             f'<td class="cx"><span data-zh>{e(v.get("sea_zh", ""))}</span>'
            f'<span data-en>{e(v.get("sea_en", ""))}</span></td>'
            f'<td class="cx"><span data-zh>{e(v.get("art_zh", ""))}</span>'
            f'<span data-en>{e(v.get("art_en", ""))}</span></td>'
            f'<td class="co"><span data-zh>{e(v.get("ref_zh", ""))}</span>'
            f'<span data-en>{e(v.get("ref_en", ""))}</span></td>'
            "</tr>"
        )
    return ('<div class="layer-bar" role="toolbar" aria-label="layer filter">'
            '<button type="button" class="lyr-btn on" data-layer="">全部 all</button>'
            + "".join(f'<button type="button" class="lyr-btn" data-layer="{e(L)}">{e(L)}</button>'
                      for L in dict.fromkeys(v.get("layer_zh", "") for v in data["vocab"] if v.get("layer_zh")))
            + "</div>"
            '<div class="gloss-wrap"><table class="gloss-table cult-table"><thead><tr>'
            "<th>音</th><th>語</th><th>分层 Layer</th><th>季語 sea</th><th>美学 art</th><th>典故 ref</th>"
            "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>"
            '<p class="cult-src" data-zh>一手出处 · 溯源：'
            '季語——<a href="https://ja.wikipedia.org/wiki/季語" target="_blank" rel="noopener">歳時記·季題分類</a>'#（季語 sea 列）
            '美学——<a href="https://ja.wikisource.org/wiki/「いき」の構造" target="_blank" rel="noopener">九鬼周造『「いき」の構造』ウィキソース全文</a>' #（美学 art 列)
            '典故——<a href="https://ja.wikipedia.org/wiki/もののあはれ" target="_blank" rel="noopener">本居宣長·もののあはれ</a>' #（典故 ref 列)</p>'
            '<p class="cult-src" data-en>primary sources: '
            '<a href="https://ja.wikipedia.org/wiki/季語" target="_blank" rel="noopener">kigo — saijiki seasonal vocabulary</a>'
             ' · <a href="https://www.aozora.gr.jp/cards/000065/files/393_1765.html" target="_blank" rel="noopener">Kuki Shūzō, The Structure of Iki</a>'
            ' · <a href="https://ja.wikipedia.org/wiki/もののあはれ" target="_blank" rel="noopener">Motoori Norinaga, mono-no-aware</a></p>'
            "</div>")


def _origin_row(c):
    """第四旋·源：字源行（平/片假名出身）。"""
    og = (f'<span class="og">{e(c.get("origin", ""))}</span>'
          f'<span class="ogk">{e(c.get("origin_k", ""))}</span>')
    note = (f'<span data-zh>{e(c.get("note_zh", ""))}</span>'
            f'<span data-en>{e(c.get("note_en", ""))}</span>')
    return ('<tr data-h="' + e(c["h"]) + '">'
            f'<td class="kc"><span class="big">{e(c["h"])}</span>'
            f'<span class="kat">{e(c["kat"])}</span>'
            f'<span class="rom">{e(c["r"])}</span></td>'
            f'<td class="og-cell">{og}</td>'
            f'<td class="onote">{note}</td>'
            "</tr>")


def origin_html(data):
    """第四旋·源：每个假名的前世（安→あ 等字源）。"""
    chart = data["chart"]
    rows = []
    for row in chart["rows"]:
        for c in row["cells"]:
            if c.get("void"):
                continue
            rows.append(_origin_row(c))
    n = chart.get("n")
    if isinstance(n, dict):
        rows.append(_origin_row(n))
    return ('<div class="gloss-wrap"><table class="gloss-table origin-table"><thead><tr>'
            "<th>音</th><th>字源 origin</th><th>注记 / Note</th>"
            "</tr></thead><tbody>" + "".join(rows) + "</tbody></table></div>")


def spiral_closure_html(data):
    """回望收束：closure + 终点回望起点 + 回到导图。"""
    s = data.get("spiral") or {}
    b = (data.get("backrefs") or {}).get("shape") or {}
    retro = (f'<p class="sc-retro" data-zh>{e(b.get("zh", ""))}</p>'
             f'<p class="sc-retro" data-en>{e(b.get("en", ""))}</p>') if b else ""
    return ('<div class="spiral-closure">'
            f'<p class="sc-word" data-zh>{e(s.get("closure_zh", ""))}</p>'
            f'<p class="sc-word" data-en>{e(s.get("closure_en", ""))}</p>'
            f'{retro}'
            '<a class="btn" href="#ring-shape"><span data-zh>&uarr; 回到第一旋 · 形</span>'
            '<span data-en>&uarr; Return to ring one · shape</span></a>'
            '<a class="btn" href="#mindmap"><span data-zh>&#8645; 回到导图</span>'
            '<span data-en>&#8645; back to the map</span></a>'
            "</div>")


def kana_index_html(data):
    """把每个假名的四旋信息（形音/词义/例句/文化/字源/分层）压成 JSON 索引。

    供前端弹窗一次性取用，避免点击跳转；以 data JSON 为单一数据源。
    """
    idx = {}

    for row in data["chart"]["rows"]:
        for c in row["cells"]:
            if c.get("void"):
                continue
            d = idx.setdefault(c["h"], {"h": c["h"]})
            for k in ("kat", "r", "note_zh", "note_en", "origin", "origin_k"):
                if c.get(k):
                    d[k] = c[k]
    n = data["chart"].get("n")
    if isinstance(n, dict):
        d = idx.setdefault(n["h"], {"h": n["h"]})
        for k in ("kat", "r", "note_zh", "note_en", "origin", "origin_k"):
            if n.get(k):
                d[k] = n[k]

    keys = ("kat", "r", "kanji", "kana", "rom", "meaning_zh", "meaning_en",
            "sent", "sent_rom", "tr_zh", "tr_en", "sea_zh", "sea_en",
            "art_zh", "art_en", "ref_zh", "ref_en", "layer_zh", "layer_en")
    for v in data["vocab"]:
        d = idx.setdefault(v["h"], {"h": v["h"]})
        for k in keys:
            if v.get(k):
                d[k] = v[k]

    payload = json.dumps(idx, ensure_ascii=False)
    payload = (payload.replace("<", "\\u003c")
                      .replace(">", "\\u003e")
                      .replace("&", "\\u0026"))
    return f'<script type="application/json" id="kana-index">{payload}</script>'


def gojuon_views(data):
    """gojuon 模块结构化视图：旋导 + 四旋（形词义源）全部锚在同一张五十音表。"""
    spiral = data.get("spiral") or {"layers": []}
    layers = {l.get("id"): l for l in spiral.get("layers", [])}

    def ring(sid, inner):
        l = layers.get(sid) or {}
        return (
            f'<section class="spiral-ring" id="ring-{e(sid)}">'
            f'<h2 class="ring-h"><span class="ring-tag">{e(l.get("zh", sid))} · {e(l.get("en", sid))}</span>'
            f'<span class="ring-title" data-zh>{e(l.get("title_zh", ""))}</span>'
            f'<span class="ring-title" data-en>{e(l.get("title_en", ""))}</span></h2>'
            f'<p class="ring-promise" data-zh>{e(l.get("promise_zh", ""))}</p>'
            f'<p class="ring-promise" data-en>{e(l.get("promise_en", ""))}</p>'
            f"{inner}</section>"
        )

    return [
        spiral_guide_html(data),
        ring("shape", kana_table_html(data) + derived_html(data) + kana_index_html(data)),
        ring("word", retro_html("word", data) + vocab_html(data)),
        ring("sense", retro_html("sense", data) + cultural_html(data)),
        ring("root", retro_html("root", data) + origin_html(data)),
        ring("law", retro_html("law", data) + prosody_html(data) + media_html(data)
             + spiral_closure_html(data)),
    ]


# 结构化数据视图注册表：data JSON 的 meta.kind → 渲染函数列表
KIND_VIEWS = {
    "gojuon": gojuon_views,
}


def module_data_blocks(lang_id, module):
    """ready 模块的结构化数据区块；无 JSON 或 kind 未注册时返回空(仅 prose)。"""
    mpath = os.path.join(DATA, lang_id, f"{module['id']}.json")
    if not os.path.exists(mpath):
        return []
    data = json.loads(read(mpath))
    kind = (data.get("meta") or {}).get("kind")
    if not kind:
        kind = module.get("kind") or module.get("id")
    view = KIND_VIEWS.get(kind)
    return view(data) if view else []


def teach_note():
    return (
        '<div class="teach-note" style="margin-top:2.2rem">'
        '<span data-zh><b>审校说明 ·</b> 教学例句（AI 起草）待母语者审校后再入正式语料；读音按标准语。</span>'
        '<span data-en><b>Review ·</b> Teaching sentences (AI-drafted) await native review before entering the formal corpus.</span>'
        "</div>"
    )


def cta_btn(href, zh, en):
    return (f'<div class="cta"><a class="btn" href="{e(href)}" data-zh>{e(zh)} &rarr;</a>'
            f'<a class="btn" href="{e(href)}" data-en>{e(en)} &rarr;</a></div>')


def rc_card(href, label):
    return f'<div class="cta" style="margin:1.2rem 0 0"><a class="btn" href="{e(href)}">{e(label)}</a></div>'


# ── 页面组装 ───────────────────────────────────────────────────
def page(css_rel, home, home_label, title, initlang, hero_html, body_html):
    return PAGE.format(
        title=title, css=css_rel, initlang=initlang, home=home, home_label=home_label,
        hero=hero_html, body=body_html,
    )


def render_hub(registry, hub_body, first_active):
    hero_html = hero(crumbs("语言叠织", "../../index.html", "语言根本", None),
                     "语种根本", "Language Roots",
                     "记读写 · 不离根本", "listen · read · write · stay rooted")
    body = render_hub_cards(registry, hub_body)
    if glossary_ready():
        body += glossary_card()
    body += cta_btn(f"{first_active}/", f"进入 {first_active}", "Enter")
    body += rc_card("../../index.html", "语言叠织 · 主页")
    return page("css/learning.css", "../../index.html", "Home",
                "语种根本 · Language Roots — 语言叠织", "lang-zh", hero_html, body)


def render_lang_index(entry, lang_meta, lang_body, first_ready=None):
    name_zh, name_en = entry["name_zh"], entry["name_en"]
    hero_html = hero(crumbs("语言根本", "../index.html", name_zh, None),
                     f"{name_zh} · 根本", f"{name_en} Roots",
                     entry["summary_zh"], entry["summary_en"])
    body = render_prose(lang_body) + module_grid(lang_meta.get("modules", []))
    if first_ready:
        body += cta_btn(f"{first_ready['id']}.html",
                        f"开始：{first_ready['name_zh']}",
                        f"Start: {first_ready['name_en']}")
    return page("../css/learning.css", "../index.html", "语言根本 | Roots",
                f"{name_zh} · 根本 — 语言叠织", "lang-zh", hero_html, body)


def render_module_page(entry, module, module_md):
    hero_html = hero(crumbs("语言根本", "../index.html",
                            entry["name_zh"], "../index.html",
                            module["name_zh"], None),
                     module["name_zh"], module["name_en"],
                     module["desc_zh"], module["desc_en"])
    body = render_prose(strip_h1(module_md))
    body += "".join(module_data_blocks(entry["id"], module))
    body += teach_note()
    title = f"{module['name_zh']} · {module['name_en']} — 语言叠织"
    return page("../css/learning.css", "../index.html", "语言根本 | Roots",
                title, "lang-zh", hero_html, body)


# ── 织网库（Core Glossary 概念权威）────────────────────────────
THREAD_KIND = {"derives_from": "沿根", "loaned_to": "借渡", "translates": "镜像"}


def load_core_glossary():
    """织网库概念权威 JSON；缺失/解析失败即报错（绝不静默出错）。"""
    if not os.path.exists(GLOSSARY_JSON):
        raise SystemExit(f"[glossary] 缺概念权威 {os.path.relpath(GLOSSARY_JSON)}")
    return json.loads(read(GLOSSARY_JSON))


def glossary_card():
    g = load_core_glossary()
    n = len(g.get("concepts", []))
    return (
        '<a class="card card-ready" href="glossary/" style="grid-column:1/-1">'
        f'<span class="glyph">织</span>'
        f'<span class="name" data-zh>织网库</span>'
        f'<span class="name" data-en>Concept Weave</span><br>'
        f'<span class="iso">{n} 概念 &times; 8 语</span>'
        f'<span class="summary" data-zh>一词而万语 · 水月心 · 词源织线</span>'
        f'<span class="summary" data-en>one word, many worlds · etymology woven</span>'
        '<span class="status ready" data-zh>织网</span>'
        '<span class="status ready" data-en>Weave</span></a>'
    )


def concept_threads(g, cid):
    """该概念的全部织线（双语 note）。"""
    out = []
    for t in g.get("threads", []):
        touched = t.get("from", "").endswith(":" + cid) or t.get("to", "").endswith(":" + cid)
        if not touched:
            continue
        kind = THREAD_KIND.get(t.get("kind"), t.get("kind", ""))
        out.append(
            f'<a class="wkind">{e(kind)}</a>'
            f'<span data-zh>{e(t.get("note_zh", ""))}</span>'
            f'<span data-en>{e(t.get("note_en", ""))}</span>'
        )
    return ("<div class=\"wthreads\">" + " &middot; ".join(out) + "</div>") if out else ""


def render_glossary_page():
    g = load_core_glossary()
    langs = g.get("languages", [])
    cards = []
    for c in g.get("concepts", []):
        terms = []
        for lang in langs:
            t = c["terms"].get(lang, {})
            roma = f'<span class="wr">{e(t.get("roma", ""))}</span>' if t.get("roma") else ""
            terms.append(
                f'<span class="wterm"><span class="wterml">{e(lang)}</span> '
                f'<span class="w">{e(t.get("word", ""))}</span>{roma}</span>'
            )
        cards.append(
            '<div class="wcard">'
            f'<div class="whead"><span class="wname" data-zh>{e(c["name_zh"])}</span>'
            f'<span class="wname" data-en>{e(c["name_en"])}</span>'
            f'<span class="wid">{e(c["id"])}</span>'
            '<span class="wtag">review pending</span></div>'
            f'<div class="words">{"".join(terms)}</div>'
            f'{concept_threads(g, c["id"])}'
            "</div>"
        )
    hero_html = hero(crumbs("语言根本", "../index.html", "织网库", None),
                     "织网库 · 概念", "Concept Weave", "一词而万语", "one word, many worlds")
    body = render_prose(strip_h1(read(GLOSSARY_MD)))
    body += f'<section class="wgrid">{"".join(cards)}</section>'
    body += teach_note()
    return page("../css/learning.css", "../index.html", "学习库 | Learning",
                "织网库 · Concept Weave — 语言叠织", "lang-zh", hero_html, body)


def glossary_ready():
    return os.path.exists(GLOSSARY_MD) and os.path.exists(GLOSSARY_JSON)


def load_registry():
    path = os.path.join(LANG, "README.md")
    registry, hub_body_md = parse_frontmatter(read(path))
    if registry is None or "languages" not in registry:
        raise SystemExit(f"[build] {os.path.relpath(path)} 缺 ---json--- frontmatter 或 languages 列表")
    return registry, hub_body_md


def langs_with_modules():
    """iterator: (entry, meta, body_md) 仅 active 语种"""
    registry, _ = load_registry()
    for entry in registry["languages"]:
        if entry.get("status") != "active":
            continue
        meta, body = parse_frontmatter(read(os.path.join(LANG, entry["id"], "README.md")))
        yield entry, meta, body


def build():
    registry, hub_body_md = load_registry()
    active = [x for x in registry["languages"] if x.get("status") == "active"]
    if not active:
        raise SystemExit("[build] 注册表无 active 语种，无法构建")
    hub_prose = render_prose(strip_h1(hub_body_md))

    pages = {os.path.join(OUT, "index.html"): render_hub(registry, hub_prose, active[0]["id"])}

    for entry, meta, body in langs_with_modules():
        modules = meta.get("modules", [])
        ready = [m for m in modules if m.get("status") == "ready"]
        base = os.path.join(OUT, entry["id"])
        pages[os.path.join(base, "index.html")] = render_lang_index(entry, meta, body,
                                                                    ready[0] if ready else None)
        for m in ready:
            md_path = os.path.join(LANG, entry["id"], f"{m['id']}.md")
            if os.path.exists(md_path):
                pages[os.path.join(base, f"{m['id']}.html")] = render_module_page(
                    entry, m, read(md_path))
    if glossary_ready():
        pages[os.path.join(OUT, "glossary", "index.html")] = render_glossary_page()
    return pages


# ── 校验（知识源）──────────────────────────────────────────────
def validate_glossary():
    """织网库 Core Glossary 结构校验（概念权威，绝不静默出错）。"""
    errors = []
    if not os.path.exists(GLOSSARY_JSON):
        errors.append("缺 core_glossary.json（织网库概念权威）")
        return errors
    try:
        g = json.loads(read(GLOSSARY_JSON))
    except ValueError as exc:
        errors.append(f"core_glossary.json 解析失败: {exc}")
        return errors
    langs = g.get("languages") or []
    if len(langs) < 2:
        errors.append("core_glossary languages 列表缺失或过短")
        return errors
    ids = []
    for c in g.get("concepts", []):
        cid = c.get("id")
        if not cid:
            errors.append("概念缺 id")
            continue
        ids.append(cid)
        for field in ("name_zh", "name_en"):
            if not c.get(field):
                errors.append(f"[{cid}] 缺字段 {field}")
        terms = c.get("terms") or {}
        missing = [l for l in langs if l not in terms]
        if missing:
            errors.append(f"[{cid}] 缺语种词位: {missing}")
        for lang, t in terms.items():
            if not isinstance(t, dict) or "word" not in t:
                errors.append(f"[{cid}/{lang}] 词位缺 word")
            if not isinstance(t, dict) or "roma" not in t:
                errors.append(f"[{cid}/{lang}] 词位缺 roma 键")
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    if dupes:
        errors.append(f"概念 id 重复: {dupes}")
    lang_set = set(langs)
    for s in g.get("scripts", []):
        if not s.get("id"):
            errors.append("script 缺 id")
            continue
        bad = [l for l in s.get("langs", []) if l not in lang_set]
        if bad:
            errors.append(f"[script {s['id']}] 语言不在注册: {bad}")
    for t in g.get("threads", []):
        if t.get("kind") not in THREAD_KIND:
            errors.append(f"[thread {t.get('id')}] kind 非法: {t.get('kind')}")
        for ref in (t.get("from"), t.get("to")):
            if not ref or not (ref.startswith("root:") or ":" in ref):
                errors.append(f"[thread {t.get('id')}] 引用格式非法: {ref!r}")
    if not g.get("meta", {}).get("review"):
        errors.append("core_glossary 缺 meta.review（审校状态必须声明）")
    return errors


def validate_sources():
    """返回错误消息列表（空 = 通过）。节奏：绝不静默出错。"""
    errors = []

    registry, hub_body = load_registry()
    langs = registry["languages"]
    if not langs:
        errors.append("hub frontmatter 缺 languages 列表")

    ids = [l.get("id") for l in langs if l.get("id")]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    if dupes:
        errors.append(f"语种 id 重复: {dupes}")

    for l in langs:
        lid = l.get("id")
        for field in ("name_zh", "name_en", "iso", "glyph", "summary_zh", "summary_en"):
            if not l.get(field):
                errors.append(f"[{lid or '?'}] 缺字段 {field}")
        if l.get("status") == "active":
            if not l.get("href"):
                errors.append(f"[{lid}] active 语种缺 href")
            # active 语种必有 README；planned 语种不允许出现学习页文件
            readme = os.path.join(LANG, lid, "README.md")
            if not os.path.exists(readme):
                errors.append(f"[{lid}] active 语种缺 {lid}/README.md")
            meta, body = parse_frontmatter(read(readme))
            if meta is None:
                errors.append(f"[{lid}] README.md 无 frontmatter")
                continue
            modules = meta.get("modules", [])
            m_ids = [m.get("id") for m in modules]
            m_dupes = sorted({i for i in m_ids if m_ids.count(i) > 1})
            if m_dupes:
                errors.append(f"[{lid}] 模块 id 重复: {m_dupes}")
            for m in modules:
                for field in ("name_zh", "name_en", "desc_zh", "desc_en"):
                    if not m.get(field):
                        errors.append(f"[{lid}/{m.get('id')}] 缺模块字段 {field}")
                if m.get("status") == "ready":
                    if m.get("href") != f"{m['id']}.html":
                        errors.append(f"[{lid}/{m['id']}] ready 模块 href 应为 {m['id']}.html")
                    mdp = os.path.join(LANG, lid, f"{m['id']}.md")
                    if not os.path.exists(mdp):
                        errors.append(f"[{lid}/{m['id']}] ready 模块缺页面源 {m['id']}.md")
                    else:
                        validate_md_bilingual(mdp, errors, lid, m["id"])
                    jpath = os.path.join(DATA, lid, f"{m['id']}.json")
                    if os.path.exists(jpath):
                        validate_module_json(jpath, errors, lid, m["id"])
                else:  # planned
                    if m.get("href") not in (None, "", "#future"):
                        errors.append(f"[{lid}/{m['id']}] planned 模块不应有实际 href")
            if body and not body.strip():
                errors.append(f"[{lid}] README 正文为空")
    errors += validate_glossary()
    if not os.path.exists(GLOSSARY_MD):
        errors.append("缺 glossary.md（织网库散文页源）")
    else:
        validate_md_bilingual(GLOSSARY_MD, errors, "glossary", "index")
    return errors


def validate_md_bilingual(path, errors, lid, mid):
    text = read(path)
    zh = len(re.findall(r"^\s*<!--\s*zh\s*-->", text, re.M))
    en = len(re.findall(r"^\s*<!--\s*en\s*-->", text, re.M))
    if zh != en:
        errors.append(f"[{lid}/{mid}] 双语标记不平衡 zh={zh} en={en}")
    if strip_h1(text) == text and not re.match(r"^#\s+.+", text):
        errors.append(f"[{lid}/{mid}] 缺 H1 标题行")


def validate_module_json(path, errors, lid, mid):
    try:
        data = json.loads(read(path))
    except ValueError as exc:
        errors.append(f"[{lid}/{mid}] JSON 解析失败: {exc}")
        return
    kind = (data.get("meta") or {}).get("kind")
    if kind and kind not in KIND_VIEWS:
        errors.append(f"[{lid}/{mid}] JSON meta.kind={kind} 未注册渲染视图(KIND_VIEWS)，页面将只有 prose")
    if "chart" in data:
        chart = data["chart"]
        for ri, row in enumerate(chart.get("rows", [])):
            for ci, c in enumerate(row.get("cells", [])):
                keys = set(c)
                if c.get("void"):
                    if keys - {"void"}:
                        errors.append(f"[{lid}/{mid}] 第{ri}行{ci}列 void 单元携带多余键 {sorted(keys - {'void'})}")
                    continue
                for field in ("h", "kat", "r"):
                    if not c.get(field):
                        errors.append(f"[{lid}/{mid}] 第{ri}行{ci}列缺字段 {field}")
    if "vocab" in data:
        for i, v in enumerate(data["vocab"]):
            for field in ("h", "kanji", "kana", "rom", "meaning_zh", "meaning_en", "sent", "sent_rom", "tr_zh", "tr_en", "r", "kat"):
                if not v.get(field):
                    errors.append(f"[{lid}/{mid}] 词表第{i}条缺字段 {field}")


# ── 产物校验 ───────────────────────────────────────────────────
def check_outputs(pages):
    ok = True
    expected = set(pages.keys())
    for path, text in pages.items():
        if not os.path.exists(path):
            print(f"[check] MISSING {path}")
            ok = False
            continue
        needles = ["data-bit"]
        rel = os.path.relpath(path, OUT)
        if "data-bit" not in text:
            ok = False
            print(f"[check] {rel} 缺 data-bit")
        for tag in ("div", "table", "span", "a", "section"):
            opens = len(re.findall(r"<" + tag + r"(?!\w)", text))
            closes = len(re.findall(r"</" + tag + r"\s*>", text))
            delta = opens - closes
            if delta:
                print(f"[check] {rel} 标签<{tag}>不平衡 ±{delta}")
                ok = False
        if len(text) < 2000:
            print(f"[check] {rel} 内容过短")
            ok = False
    # 陈旧产物检测：OUT 下存在但本次未声明的 .html
    stale = set()
    for root, _dirs, files in os.walk(OUT):
        for fn in files:
            if fn.endswith(".html"):
                full = os.path.join(root, fn)
                if full not in expected:
                    stale.add(full)
    if stale:
        ok = False
        for s in sorted(stale):
            print(f"[check] 陈旧产物(不在本次构建): {s}")
    return ok


# ── sqlite 索引 ───────────────────────────────────────────────
def sync_sqlite(registry, langs_modules, db_path=None):
    import sqlite3
    db_path = db_path or os.path.join(DATA, "learning.db")
    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    con = sqlite3.connect(db_path)
    cur = con.cursor()
    cur.execute("""CREATE TABLE IF NOT EXISTS meta(
        key TEXT PRIMARY KEY, value TEXT)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS languages(
        id TEXT PRIMARY KEY, glyph TEXT, name_zh TEXT, name_en TEXT,
        iso TEXT, status TEXT, summary_zh TEXT, summary_en TEXT, href TEXT)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS modules(
        id TEXT, lang TEXT, href TEXT, status TEXT,
        name_zh TEXT, name_en TEXT, PRIMARY KEY(id, lang))""")
    cur.execute("""CREATE TABLE IF NOT EXISTS chart_cells(
        lang TEXT, module TEXT, row TEXT, col INTEGER, h TEXT, kata TEXT,
        roma TEXT, note TEXT, PRIMARY KEY(lang, module, row, col))""")
    cur.execute("""CREATE TABLE IF NOT EXISTS vocab(
        lang TEXT, module TEXT, id TEXT, hira TEXT, kata TEXT, roma TEXT,
        kanji TEXT, kana TEXT, meaning_zh TEXT, meaning_en TEXT,
        sentence TEXT, sent_rom TEXT, tr_zh TEXT, tr_en TEXT,
        PRIMARY KEY(lang, module, id))""")
    cur.execute("""CREATE TABLE IF NOT EXISTS accent_types(
        id TEXT PRIMARY KEY, lang TEXT, module TEXT, num INTEGER,
        name_zh TEXT, name_en TEXT, seq TEXT, zh TEXT, en TEXT)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS mpairs(
        id TEXT PRIMARY KEY, lang TEXT, module TEXT, kind TEXT, idx INTEGER,
        a_kana TEXT, a_rom TEXT, b_kana TEXT, b_rom TEXT, c_kana TEXT, c_rom TEXT,
        zh TEXT, en TEXT, src TEXT)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS media_links(
        id TEXT PRIMARY KEY, lang TEXT, module TEXT, kind TEXT,
        title_zh TEXT, title_en TEXT, url TEXT, note_zh TEXT, note_en TEXT)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS concepts(
        id TEXT PRIMARY KEY, name_zh TEXT, name_en TEXT, probe INTEGER DEFAULT 0)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS concept_terms(
        concept TEXT, lang TEXT, word TEXT, roma TEXT,
        PRIMARY KEY(concept, lang))""")
    cur.execute("""CREATE TABLE IF NOT EXISTS scripts(
        id TEXT PRIMARY KEY, name_zh TEXT, name_en TEXT,
        note_zh TEXT, note_en TEXT, langs TEXT)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS threads(
        id TEXT PRIMARY KEY, kind TEXT, from_ref TEXT, to_ref TEXT,
        note_zh TEXT, note_en TEXT)""")
    cur.execute("DELETE FROM languages")
    cur.execute("DELETE FROM modules")
    cur.execute("DELETE FROM chart_cells")
    cur.execute("DELETE FROM vocab")
    cur.execute("DELETE FROM accent_types")
    cur.execute("DELETE FROM mpairs")
    cur.execute("DELETE FROM media_links")
    _sync_glossary(cur)
    cur.executemany("INSERT INTO languages VALUES(:id,:glyph,:name_zh,:name_en,:iso,:status,:summary_zh,:summary_en,:href)",
                    [{"id": l["id"], **{k: l.get(k, "") for k in ("glyph", "name_zh", "name_en", "iso", "status", "summary_zh", "summary_en", "href")}}
                     for l in registry["languages"]])
    for lang_id, modules in langs_modules.items():
        for m in modules:
            cur.execute("INSERT INTO modules VALUES(?,?,?,?,?,?)",
                        (m["id"], lang_id, m.get("href", ""), m.get("status", "planned"),
                         m.get("name_zh", ""), m.get("name_en", "")))
            jpath = os.path.join(DATA, lang_id, f"{m['id']}.json")
            if os.path.exists(jpath):
                data = json.loads(read(jpath))
                _sync_chart(cur, lang_id, m["id"], data)
                _sync_vocab(cur, lang_id, m["id"], data)
                _sync_prosody(cur, lang_id, m["id"], data)
                _sync_media(cur, lang_id, m["id"], data)
    cur.execute("INSERT OR REPLACE INTO meta VALUES('schema_version','1')")
    cur.execute("INSERT OR REPLACE INTO meta VALUES('builder','build_learning.py')")
    con.commit()
    con.close()
    print(f"[db] 学习库索引已同步: {db_path}")


def _sync_glossary(cur):
    """织网库 Core Glossary → concepts/concept_terms/scripts/threads 表。"""
    g = load_core_glossary()
    for c in g.get("concepts", []):
        cur.execute("INSERT OR REPLACE INTO concepts VALUES(?,?,?,0)",
                    (c["id"], c.get("name_zh", ""), c.get("name_en", "")))
        for lang, t in (c.get("terms") or {}).items():
            cur.execute("INSERT OR REPLACE INTO concept_terms VALUES(?,?,?,?)",
                        (c["id"], lang, t.get("word", ""), t.get("roma", "")))
    for s in g.get("scripts", []):
        cur.execute("INSERT OR REPLACE INTO scripts VALUES(?,?,?,?,?,?)",
                    (s["id"], s.get("name_zh", ""), s.get("name_en", ""),
                     s.get("note_zh", ""), s.get("note_en", ""),
                     ",".join(s.get("langs", []))))
    for t in g.get("threads", []):
        cur.execute("INSERT OR REPLACE INTO threads VALUES(?,?,?,?,?,?)",
                    (t["id"], t["kind"], t["from"], t["to"],
                     t.get("note_zh", ""), t.get("note_en", "")))


def _sync_chart(cur, lang_id, module_id, data):
    chart = data.get("chart") or {}
    for ri, row in enumerate(chart.get("rows", [])):
        for ci, c in enumerate(row.get("cells", [])):
            note = ""
            if c.get("void"):
                note = "void"
            elif c.get("particle"):
                note = "particle"
            cur.execute(
                "INSERT OR REPLACE INTO chart_cells VALUES(?,?,?,?,?,?,?,?)",
                (lang_id, module_id, row.get("row", ""), ci,
                 (c.get("h") or ""), (c.get("kat") or ""), (c.get("r") or ""), note))
    n = chart.get("n")
    if isinstance(n, dict):
        cur.execute(
            "INSERT OR REPLACE INTO chart_cells VALUES(?,?,?,?,?,?,?,?)",
            (lang_id, module_id, "n", 0,
             (n.get("h") or ""), (n.get("kat") or ""), (n.get("r") or ""), ""))


def _sync_vocab(cur, lang_id, module_id, data):
    for v in data.get("vocab", []):
        cur.execute(
            "INSERT OR REPLACE INTO vocab VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (lang_id, module_id, v.get("h", ""), v.get("h", ""), v.get("kat", ""), v.get("r", ""),
             v.get("kanji", ""), v.get("kana", ""), v.get("meaning_zh", ""), v.get("meaning_en", ""),
             v.get("sent", ""), v.get("sent_rom", ""), v.get("tr_zh", ""), v.get("tr_en", "")))


def _sync_prosody(cur, lang_id, module_id, data):
    """第五旋·律 → accent_types / mpairs 表（逐词音调只存出处，不臆造）。"""
    p = data.get("prosody") or {}
    for acc in p.get("accent_types", []):
        cur.execute("INSERT OR REPLACE INTO accent_types VALUES(?,?,?,?,?,?,?,?,?)",
                    (f"{lang_id}:{module_id}:acc:{acc.get('num')}", lang_id, module_id,
                     acc.get("num"), acc.get("name_zh", ""), acc.get("name_en", ""),
                     acc.get("seq", ""), acc.get("zh", ""), acc.get("en", "")))
    for i, mp in enumerate(p.get("minimal_pairs", [])):
        a, b, c = mp.get("a") or {}, mp.get("b") or {}, mp.get("c") or {}
        cur.execute("INSERT OR REPLACE INTO mpairs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                    (f"{lang_id}:{module_id}:pair:{i}", lang_id, module_id,
                     mp.get("kind", ""), i,
                     a.get("kana", ""), a.get("rom", ""), b.get("kana", ""), b.get("rom", ""),
                     c.get("kana", ""), c.get("rom", ""),
                     mp.get("zh", ""), mp.get("en", ""), mp.get("src", "")))


def _sync_media(cur, lang_id, module_id, data):
    """媒体/拓展 → media_links 表（图/影/读三类统一为资源链接）。"""
    md = data.get("media") or {}
    rows = []
    img = md.get("image") or {}
    if img:
        rows.append(("image", img.get("cap_zh", ""), img.get("cap_en", ""),
                     img.get("url", ""), "", ""))
    vid = md.get("video") or {}
    if vid:
        rows.append(("video", vid.get("title_zh", ""), vid.get("title_en", ""),
                     vid.get("url", ""), vid.get("note_zh", ""), vid.get("note_en", "")))
    for r in md.get("read", []):
        rows.append(("read", r.get("zh", ""), r.get("en", ""),
                     r.get("url", ""), r.get("note_zh", ""), r.get("note_en", "")))
    for i, (kind, tz, te, url, nz, ne) in enumerate(rows):
        cur.execute("INSERT OR REPLACE INTO media_links VALUES(?,?,?,?,?,?,?,?,?)",
                    (f"{lang_id}:{module_id}:{kind}:{i}", lang_id, module_id,
                     kind, tz, te, url, nz, ne))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--validate", action="store_true", help="校验知识源")
    ap.add_argument("--db", action="store_true", help="同步 sqlite 查询索引")
    ap.add_argument("--check", action="store_true", help="源校验 + 产物校验")
    args = ap.parse_args()

    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    if args.validate or args.check:
        errs = validate_sources()
        if errs:
            print("[validate] 发现 %d 处错误:" % len(errs))
            for er in errs:
                print("  [ERR]", er)
            sys.exit(1)
        print("[validate] 知识源通过")

    os.makedirs(os.path.dirname(CSS_OUT), exist_ok=True)
    if os.path.exists(CSS_SRC) and read(CSS_SRC).strip():
        write(CSS_OUT, read(CSS_SRC))

    pages = build()
    for path, text in pages.items():
        write(path, text)
    print(f"[build] 已生成 {len(pages)} 页 -> {OUT}")

    if args.db:
        registry, _ = load_registry()
        langs_modules = {}
        for entry in registry["languages"]:
            if entry.get("status") != "active":
                continue
            meta, _body = parse_frontmatter(
                read(os.path.join(LANG, entry["id"], "README.md")))
            langs_modules[entry["id"]] = (meta or {}).get("modules", [])
        sync_sqlite(registry, langs_modules)

    if args.check:
        ok = check_outputs(pages)
        sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()