#!/usr/bin/env python3
"""Language Stacking: 学习库静态站点生成器（registry 驱动）

读取 languages/ 下的 markdown(prose + frontmatter) 与 data/ 下的 JSON(结构化数据),
按 languages/README.md 的语种注册表(frontmatter)泛化渲染学习库三级子站:
  learning/index.html            (hub，来自 registry)
  learning/{lang}/index.html     (每 active 语种的索引，来自 {lang}/README.md + modules)
  learning/{lang}/{module}.html  (每 ready 模块页，prose 来自 {lang}/{module}.md，
                                 结构化数据由 meta.kind 对应 KIND_VIEWS 渲染)

用法:
  conda activate hy_py312
  python "Language Stacking-Linguistic Weaving/web/build_learning.py" [--validate] [--db] [--check]

功能:
  --validate  校验知识源（frontmatter/模块一致性/双语标记平衡/JSON schema/链接解析）
  --db        同步 sqlite 查询索引 languages/data/learning.db（语言+模块+音图+词表+织网库）
  --check     源校验 + 产物校验（存在性/关键组件/标签平衡/陈旧产物检测）

标准库之外仅依赖 markdown 包与(可选)pytest。内容数据不硬编码：一律来自 languages/**。
"""
import argparse
import html
import json
import os
import re
import sys

try:
    import markdown
except ImportError as exc:  # pragma: no cover
    sys.exit(f"[build_learning] 缺少依赖: {exc}  (请 conda activate hy_py312)")

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DOMAIN = os.path.join(REPO, "Language Stacking-Linguistic Weaving")
LANG    = os.path.join(DOMAIN, "languages")
DATA    = os.path.join(LANG, "data")
OUT     = os.path.join(REPO, "docs", "language_stacking", "learning")
CSS_SRC = os.path.join(HERE, "css", "learning.css")
CSS_OUT = os.path.join(OUT, "css", "learning.css")
GLOSSARY_MD   = os.path.join(LANG, "glossary.md")
GLOSSARY_JSON = os.path.join(DATA, "core_glossary.json")

MD = markdown.Markdown(extensions=["tables", "fenced_code", "attr_list", "toc", "sane_lists"])


# ── shell 模板 ────────────────────────────────────────────────
PAGE = """<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=LXGW+WenKai:wght@400;700&family=Inter:wght@400;500;600;700&family=Noto+Serif+JP:wght@400;600&family=Noto+Sans+JP:wght@400;500&family=EB+Garamond:ital,wght@0,400;0,500;1,400&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{css}">
</head>
<body class="{initlang}">
<header class="nav">
  <div class="nav-brand"><span data-zh>语言叠织</span><span data-en>Language Stacking</span><span class="sub">&middot; 学习库 Learning</span></div>
  <div class="nav-right">
    <a class="nav-home" href="{home}">{home_label}</a>
    <div class="lang-toggle" aria-label="language">
      <button data-lang="zh" type="button">中</button>
      <button data-lang="en" type="button">EN</button>
    </div>
  </div>
</header>
<main>
{hero}
<div class="wrap">
{body}
</div>
</main>
<footer class="footer">
  <p><span data-zh>《语言叠织 · Language Stacking》 语种根本 · 所有学习与使用不离根本</span><span data-en>Language Stacking — per-language Roots · learning and use stay rooted</span></p>
  <p class="note"><span data-zh>本页由 build_learning.py 从 languages/ 知识源自动生成 · 内容以知识库为单一来源</span><span data-en>Generated by build_learning.py from the languages/ knowledge base · single source of truth</span></p>
</footer>
<script>
(function () {{
  const key = 'ls-lang';
  const saved = (() => {{ try {{ return localStorage.getItem(key); }} catch (e) {{ return null; }} }})();
  document.body.classList.add(saved === 'en' ? 'lang-en' : 'lang-zh');
  function set(lang) {{
    document.body.classList.toggle('lang-en', lang === 'en');
    document.body.classList.toggle('lang-zh', lang === 'zh');
    document.querySelectorAll('.lang-toggle button').forEach(function (b) {{
      b.classList.toggle('active', b.getAttribute('data-lang') === lang);
    }});
    try {{ localStorage.setItem(key, lang); }} catch (e) {{}}
  }}
  set(document.body.classList.contains('lang-en') ? 'en' : 'zh');
  document.querySelectorAll('.lang-toggle button').forEach(function (b) {{
    b.addEventListener('click', function () {{ set(b.getAttribute('data-lang')); }});
  }});
  window.addEventListener('scroll', function () {{
    document.querySelector('header.nav').classList.toggle('scrolled', window.scrollY > 8);
  }});
  window._lastKanaVoice = null;
  function kanaVoiceScore(v) {{
    var n = (v.name || '').toLowerCase();
    if (n.indexOf('natural') >= 0 || n.indexOf('neural') >= 0) return 10;
    if (n.indexOf('online') >= 0 || n.indexOf('premium') >= 0) return 8;
    if (n.indexOf('google') >= 0) return 6;
    if (n.indexOf('desktop') >= 0) return 4;
    return 0;
  }}
  function jaVoices() {{
    try {{
      var raw = speechSynthesis.getVoices();
      var arr = [];
      for (var i = 0; i < raw.length; i++) arr.push(raw[i]);
      var vs = arr.filter(function (v) {{
        return (v.lang || '').replace(/_/g, '-').toLowerCase().indexOf('ja') === 0;
      }});
      vs.sort(function (a, b) {{ return kanaVoiceScore(b) - kanaVoiceScore(a); }});
      return vs;
    }} catch (e) {{ return []; }}
  }}
  function resolveVoice(uri) {{
    if (!uri) return null;
    var vs = speechSynthesis.getVoices();
    for (var i = 0; i < vs.length; i++) {{
      if (vs[i].voiceURI === uri) return vs[i];
    }}
    return null;
  }}
  window.kanaSpeak = function (kana, voiceURI) {{
    try {{
      var u = new SpeechSynthesisUtterance(kana);
      u.lang = 'ja-JP';
      u.rate = 0.8;
      u.pitch = 1.0;
      var v = resolveVoice(voiceURI);
      if (!v) v = resolveVoice(window._lastKanaVoice);
      if (!v) {{
        var vs = jaVoices();
        if (vs.length) v = vs[0];
      }}
      if (v) {{ u.voice = v; window._lastKanaVoice = v.voiceURI; }}
      speechSynthesis.cancel();
      speechSynthesis.speak(u);
    }} catch (e) {{}}
  }};
  function fillKanaVoices() {{
    var boxes = document.querySelectorAll('.kana-voices');
    if (!boxes.length) return;
    var vs = jaVoices();
    boxes.forEach(function (box) {{
      box.innerHTML = '';
      var kana = box.getAttribute('data-h');
      vs.forEach(function (v) {{
        var b = document.createElement('button');
        b.type = 'button';
        b.className = 'voice-btn';
        b.title = v.name;
        var m = v.name.match(/[\u4e00-\u9fff\u3040-\u30ffa-zA-Z][\u4e00-\u9fff\u3040-\u30ffa-zA-Z ]+/);
        var label = m ? m[0].replace(/ /g, '') : v.name;
        b.textContent = label.length > 12 ? label.slice(0, 12) + '\u2026' : label;
        b.addEventListener('click', function (ev) {{
          ev.stopPropagation();
          window._lastKanaVoice = v.voiceURI;
          window.kanaSpeak(kana, v.voiceURI);
        }});
        box.appendChild(b);
      }});
    }});
  }}
  if ('speechSynthesis' in window) {{
    fillKanaVoices();
    try {{ speechSynthesis.onvoiceschanged = fillKanaVoices; }} catch (e) {{}}
  }}
}})();
</script>
</body>
</html>
"""


# ── 工具 ───────────────────────────────────────────────────────
def e(s):
    return html.escape(str(s), quote=True)


def read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def parse_frontmatter(text):
    """顶部 ---json ... --- frontmatter → (dict|None, body)"""
    m = re.match(r"^---json\s*\n(.*?)\n---\s*\n?", text, re.S)
    if not m:
        return None, text
    return json.loads(m.group(1)), text[m.end():]


def strip_h1(md):
    """去掉第一个 '# ' 标题行(页面体现为 hero, 不重复占 h1)"""
    return re.sub(r"^# .*\n+", "", md, count=1)


def render_prose(md_body):
    """多段双语 markdown → HTML。无标记段 = 共享段（zh/en 双份）。"""
    pattern = re.compile(r"^\s*<!--\s*(zh|en)\s*-->\s*$", re.M)
    parts = pattern.split(md_body)
    out = []
    if parts[0].strip():
        h = _render_md(parts[0])
        out.append(f'<div data-both="1"><div data-bit="zh">{h}</div><div data-bit="en">{h}</div></div>')
    for i in range(1, len(parts), 2):
        bit, chunk = parts[i], parts[i + 1]
        if not chunk.strip():
            continue
        out.append(f'<div data-both="1"><div data-bit="{bit}">{_render_md(chunk)}</div></div>')
    return "".join(out)


def _render_md(md_text):
    MD.reset()
    return MD.convert(md_text).strip()


def zh_en(text_zh, text_en):
    return f'<span data-zh>{e(text_zh)}</span><span data-en>{e(text_en)}</span>'


# ── 组件 ───────────────────────────────────────────────────────
def crumbs(*segments):
    """(label, href|None, label, href|None, ...) 扁平行参 → 面包屑 HTML，以 › 分隔"""
    parts = []
    for i in range(0, len(segments) - 1, 2):
        label, href = segments[i], segments[i + 1]
        if href:
            parts.append(f'<a href="{e(href)}">{e(label)}</a>')
        else:
            parts.append(f"<span>{e(label)}</span>")
    return " &rsaquo; ".join(parts)


def hero(crumb, h1_zh, h1_en, sub_zh, sub_en):
    return (
        '<section class="learn-hero">'
        f"<p class=\"crumb\">{crumb}</p>"
        f'<h1>{e(h1_zh)}</h1>'
        f'<p class="sub">{e(sub_zh)} &middot; {e(sub_en)}</p>'
        "</section>"
    )


def lcard(lang):
    ready = lang.get("status") == "active"
    stat = "ready" if ready else "planned"
    stat_zh, stat_en = ("学习入口" if ready else "建设中"), ("Enter" if ready else "Planned")
    glyph = f'<span class="glyph">{e(lang["glyph"])}</span>'
    name_zh = f'<span class="name" data-zh>{e(lang["name_zh"])}</span>'
    name_en = f'<span class="name" data-en>{e(lang["name_en"])}</span>'
    summary = (f'<span class="summary" data-zh>{e(lang["summary_zh"])}</span>'
               f'<span class="summary" data-en>{e(lang["summary_en"])}</span>')
    stat_tag = (f'<span class="status {stat}" data-zh>{stat_zh}</span>'
                f'<span class="status {stat}" data-en>{stat_en}</span>')
    enter = "" if not ready else (
        f'<a class="enter" href="{e(lang["href"])}" data-zh>进入学习 &rarr;</a>'
        f'<a class="enter" href="{e(lang["href"])}" data-en>Enter &rarr;</a>'
    )
    href = e(lang["href"]) if ready else "#future"
    return (f'<a class="card card-{stat}" href="{href}">{glyph}{name_zh}{name_en}<br>'
            f'<span class="iso">{e(lang["iso"])}</span>{summary}{stat_tag}{enter}</a>')


def render_hub_cards(registry, prose):
    langs = registry["languages"]
    active = [x for x in langs if x.get("status") == "active"]
    planned = [x for x in langs if x.get("status") != "active"]
    cards = "".join(lcard(x) for x in active + planned)
    return prose + f'<section class="cards" aria-label="languages">{cards}</section>'


def mcard(module):
    ready = module.get("status") == "ready"
    body = (
        f'<span class="name" data-zh>{e(module["name_zh"])}</span>'
        f'<span class="name" data-en>{e(module["name_en"])}</span><br>'
        f'<span class="summary" data-zh>{e(module["desc_zh"])}</span>'
        f'<span class="summary" data-en>{e(module["desc_en"])}</span>'
        f'<span class="status {"ready" if ready else "planned"}" data-zh>{"可学" if ready else "筹备中"}</span>'
        f'<span class="status {"ready" if ready else "planned"}" data-en>{"Ready" if ready else "Coming"}</span>'
    )
    if ready:
        return f'<a class="card card-ready" href="{e(module["href"])}">{body}</a>'
    return f'<span class="card card-planned" aria-disabled="true">{body}</span>'


def module_grid(modules):
    return f'<section class="cards" aria-label="modules" style="max-width:820px">{"".join(mcard(m) for m in modules)}</section>'


def kana_origin_line(c):
    """tooltip 内的字源行（第四旋·源 在每一格上留下的回望线索）。"""
    if not (c.get("origin") or c.get("origin_k")):
        return ""
    o = e(c.get("origin", ""))
    ok = e(c.get("origin_k", ""))
    return (f'<span class="kana-origin"><span data-zh>字源 {o} / {ok}</span>'
            f'<span data-en>origin {o} / {ok}</span></span>')


def kana_table_html(data):
    chart = data["chart"]
    hdr = "<th></th>" + "".join(
        f'<th class="vowel">{e(col[0])}<span class="r">{e(col[1])}</span></th>'
        for col in chart["columns"]
    )
    rows = []
    for row in chart["rows"]:
        cells = []
        for c in row["cells"]:
            if c.get("void"):
                cells.append('<td class="kana-cell void"><span>&mdash;</span></td>')
                continue
            cls = "kana-cell" + (" particle" if c.get("particle") else "")
            tip = ""
            note_zh = c.get("note_zh", "")
            note_en = c.get("note_en", "")
            if note_zh or note_en or c.get("origin") or c.get("origin_k"):
                tip = (
                    f'<span class="kana-tip">'
                    f'<span data-zh>{e(note_zh)}</span>'
                    f'<span data-en>{e(note_en)}</span>'
                    f'{kana_origin_line(c)}'
                    f'<span class="kana-voices" data-h="{e(c["h"])}" data-r="{e(c["r"])}"></span>'
                    f'</span>'
                )
            cells.append(
                f'<td class="{cls}" onclick="kanaSpeak(\'{e(c["h"])}\')" data-h="{e(c["h"])}" data-r="{e(c["r"])}">'
                f'<span class="kat">{e(c["kat"])}</span>'
                f'<span class="h">{e(c["h"])}</span>'
                f'<span class="r">{e(c["r"])}</span>'
                f'{tip}'
                f"</td>"
            )
        roma = row["cells"][0].get("r", "")[:1]
        rows.append(
            f'<tr><td class="rowname">{e(row["row"])}<span class="r">{e(roma)}</span></td>'
            f'{"".join(cells)}</tr>'
        )
    n = chart["n"]
    ntip = ""
    if n.get("note_zh") or n.get("note_en") or n.get("origin") or n.get("origin_k"):
        ntip = (
            f'<span class="kana-tip">'
            f'<span data-zh>{e(n.get("note_zh", ""))}</span>'
            f'<span data-en>{e(n.get("note_en", ""))}</span>'
            f'{kana_origin_line(n)}'
            f'<span class="kana-voices" data-h="{e(n["h"])}" data-r="{e(n["r"])}"></span>'
            f'</span>'
        )
    rows.append(
        f'<tr><td class="rowname">{e(n["h"])}<span class="r">{e(n["r"])}</span></td>'
        f'<td colspan="5" class="kana-cell" onclick="kanaSpeak(\'{e(n["h"])}\')" data-h="{e(n["h"])}" data-r="{e(n["r"])}">'
        f'<span class="kat">{e(n["kat"])}</span><span class="h">{e(n["h"])}</span><span class="r">{e(n["r"])}</span>'
        f'{ntip}'
        f"</td></tr>"
    )
    notes = chart.get("notes", {})
    zh_notes = " ".join(filter(None, [notes.get("void_zh"), notes.get("particle_zh")]))
    en_notes = " ".join(filter(None, [notes.get("void_en"), notes.get("particle_en")]))
    return (
        "<div class='kana-wrap'>"
        f"<table class='kana-table'><thead><tr>{hdr}</tr></thead><tbody>{''.join(rows)}</tbody></table>"
        + (f'<div class="kana-notes" data-zh>{e(zh_notes)}</div>' if zh_notes else "")
        + (f'<div class="kana-notes" data-en>{e(en_notes)}</div>' if en_notes else "")
        + '</div>'
    )


def derived_html(data):
    chips = []
    for d in data["derived"]:
        note_zh = f'<span class="dnote" data-zh>{e(d["note_zh"])}</span>' if d.get("note_zh") else ""
        note_en = f'<span class="dnote" data-en>{e(d["note_en"])}</span>' if d.get("note_en") else ""
        chips.append(
            f'<span>'
            f'<b class="dl" data-zh>{e(d["name_zh"])}</b>'
            f'<b class="dl" data-en>{e(d["name_en"])}</b>'
            f'<span class="dname">{e(d["kana"])}</span>{note_zh}{note_en}'
            f"</span>"
        )
    return f'<div class="derived">{"".join(chips)}</div>'


def vocab_html(data):
    rows = []
    for v in data["vocab"]:
        rows.append(
            "<tr>"
            f'<td class="kc"><span class="big">{e(v["h"])}</span>'
            f'<span class="kat">{e(v["kat"])}</span>'
            f'<span class="rom">{e(v["r"])}</span></td>'
            f'<td><span class="kw2">{e(v["kanji"])}</span> '
            f'<span class="furigana">{e(v["kana"])}</span>'
            f'<span class="rom">{e(v["rom"])}</span><br>'
            f'<span class="min-tr" data-zh>{e(v["meaning_zh"])}</span>'
            f'<span class="min-tr" data-en>{e(v["meaning_en"])}</span></td>'
            f'<td class="sent"><span lang="ja">{e(v["sent"])}</span>'
            f'<span class="rom">{e(v["sent_rom"])}</span>'
            f'<span class="tr" data-zh>{e(v["tr_zh"])}</span>'
            f'<span class="tr" data-en>{e(v["tr_en"])}</span></td>'
            "</tr>"
        )
    return (
        '<div class="gloss-wrap"><table class="gloss-table"><thead><tr>'
        "<th>音</th><th>語</th><th>例句 / Example</th>"
        "</tr></thead><tbody>"
        + "".join(rows)
        + "</tbody></table></div>"
    )


# ── 四旋螺环（spiral·同芯回望）──────────────────────────────
def spiral_guide_html(data):
    """旋导：tale + 四旋达 / 回到第一旋的提示（顶部导航）。"""
    s = data.get("spiral") or {}
    layers = s.get("layers") or []
    pills = []
    for i, l in enumerate(layers, 1):
        pills.append(
            f'<a class="pill" href="#ring-{e(l.get("id", ""))}">'
            f'<b>{i}</b>'
            f'<span class="pz" data-zh>{e(l.get("zh", ""))}</span>'
            f'<span class="pz" data-en>{e(l.get("en", ""))}</span>'
            f'<span class="pt" data-zh>{e(l.get("title_zh", ""))}</span>'
            f'<span class="pt" data-en>{e(l.get("title_en", ""))}</span>'
            f'<span class="pp" data-zh>{e(l.get("promise_zh", ""))}</span>'
            f'<span class="pp" data-en>{e(l.get("promise_en", ""))}</span></a>'
        )
    tale = (f'<p class="spiral-tale" data-zh>{e(s.get("tale_zh", ""))}</p>'
            f'<p class="spiral-tale" data-en>{e(s.get("tale_en", ""))}</p>')
    return (f'<section class="spiral-guide" id="spiral-top">'
            f'<h2 class="ring-h"><span class="ring-tag">旋 · Spiral</span>'
            f'<span data-zh>同一张表，四圈深意</span><span data-en>one chart, four rings deep</span></h2>'
            f'{tale}'
            f'<nav class="spiral-pills">{"".join(pills)}</nav>'
            f'<p class="spiral-hint" data-zh>学到第四旋，回到第一旋——同一个音会露出新的深度。</p>'
            f'<p class="spiral-hint" data-en>Finish ring four, return to ring one — the same sound is deeper now.</p>'
            f'</section>')


def cultural_html(data):
    """第三旋·义：季语（岁时）/ 美学一言 / 文化典故 坐标表。"""
    rows = []
    for v in data["vocab"]:
        rows.append(
            "<tr>"
            f'<td class="kc"><span class="big">{e(v["h"])}</span>'
            f'<span class="kat">{e(v["kat"])}</span>'
            f'<span class="rom">{e(v["r"])}</span></td>'
            f'<td><span class="kw2">{e(v["kanji"])}</span> '
            f'<span class="furigana">{e(v["kana"])}</span>'
            f'<span class="rom">{e(v["rom"])}</span><br>'
            f'<span class="min-tr" data-zh>{e(v["meaning_zh"])}</span>'
            f'<span class="min-tr" data-en>{e(v["meaning_en"])}</span></td>'
            f'<td class="cx"><span data-zh>{e(v.get("sea_zh", ""))}</span>'
            f'<span data-en>{e(v.get("sea_en", ""))}</span></td>'
            f'<td class="cx"><span data-zh>{e(v.get("art_zh", ""))}</span>'
            f'<span data-en>{e(v.get("art_en", ""))}</span></td>'
            f'<td class="co"><span data-zh>{e(v.get("ref_zh", ""))}</span>'
            f'<span data-en>{e(v.get("ref_en", ""))}</span></td>'
            "</tr>"
        )
    return ('<div class="gloss-wrap"><table class="gloss-table cult-table"><thead><tr>'
            "<th>音</th><th>語</th><th>季語 sea</th><th>美学 art</th><th>典故 ref</th>"
            "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>"
            '<p class="cult-src" data-zh>一手出处 · 溯源：'
            '季語——<a href="https://ja.wikipedia.org/wiki/季語" target="_blank" rel="noopener">歳時記·季題分類</a>'#（季語 sea 列）
            '美学——<a href="https://ja.wikisource.org/wiki/「いき」の構造" target="_blank" rel="noopener">九鬼周造『「いき」の構造』ウィキソース全文</a>' #（美学 art 列)
            '典故——<a href="https://ja.wikipedia.org/wiki/もののあはれ" target="_blank" rel="noopener">本居宣長·もののあはれ</a>' #（典故 ref 列)</p>'
            '<p class="cult-src" data-en>primary sources: '
            '<a href="https://ja.wikipedia.org/wiki/季語" target="_blank" rel="noopener">kigo — saijiki seasonal vocabulary</a>'
             ' · <a href="https://www.aozora.gr.jp/cards/000065/files/393_1765.html" target="_blank" rel="noopener">Kuki Shūzō, The Structure of Iki</a>'
            ' · <a href="https://ja.wikipedia.org/wiki/もののあはれ" target="_blank" rel="noopener">Motoori Norinaga, mono-no-aware</a></p>'
            "</div>")


def _origin_row(c):
    """第四旋·源：字源行（平/片假名出身）。"""
    og = (f'<span class="og">{e(c.get("origin", ""))}</span>'
          f'<span class="ogk">{e(c.get("origin_k", ""))}</span>')
    note = (f'<span data-zh>{e(c.get("note_zh", ""))}</span>'
            f'<span data-en>{e(c.get("note_en", ""))}</span>')
    return ("<tr>"
            f'<td class="kc"><span class="big">{e(c["h"])}</span>'
            f'<span class="kat">{e(c["kat"])}</span>'
            f'<span class="rom">{e(c["r"])}</span></td>'
            f'<td class="og-cell">{og}</td>'
            f'<td class="onote">{note}</td>'
            "</tr>")


def origin_html(data):
    """第四旋·源：每个假名的前世（安→あ 等字源）。"""
    chart = data["chart"]
    rows = []
    for row in chart["rows"]:
        for c in row["cells"]:
            if c.get("void"):
                continue
            rows.append(_origin_row(c))
    n = chart.get("n")
    if isinstance(n, dict):
        rows.append(_origin_row(n))
    return ('<div class="gloss-wrap"><table class="gloss-table origin-table"><thead><tr>'
            "<th>音</th><th>字源 origin</th><th>注记 / Note</th>"
            "</tr></thead><tbody>" + "".join(rows) + "</tbody></table></div>")


def spiral_closure_html(data):
    """回望收束：closure + 回到第一旋的按钮。"""
    s = data.get("spiral") or {}
    return ('<div class="spiral-closure">'
            f'<p class="sc-word" data-zh>{e(s.get("closure_zh", ""))}</p>'
            f'<p class="sc-word" data-en>{e(s.get("closure_en", ""))}</p>'
            f'<a class="btn" href="#ring-shape" data-zh>&uarr; 回到第一旋 · 形</a>'
            f'<a class="btn" href="#ring-shape" data-en>&uarr; Return to ring one · shape</a>'
            "</div>")


def gojuon_views(data):
    """gojuon 模块结构化视图：旋导 + 四旋（形词义源）全部锚在同一张五十音表。"""
    spiral = data.get("spiral") or {"layers": []}
    layers = {l.get("id"): l for l in spiral.get("layers", [])}

    def ring(sid, inner):
        l = layers.get(sid) or {}
        return (
            f'<section class="spiral-ring" id="ring-{e(sid)}">'
            f'<h2 class="ring-h"><span class="ring-tag">{e(l.get("zh", sid))} · {e(l.get("en", sid))}</span>'
            f'<span class="ring-title" data-zh>{e(l.get("title_zh", ""))}</span>'
            f'<span class="ring-title" data-en>{e(l.get("title_en", ""))}</span></h2>'
            f'<p class="ring-promise" data-zh>{e(l.get("promise_zh", ""))}</p>'
            f'<p class="ring-promise" data-en>{e(l.get("promise_en", ""))}</p>'
            f"{inner}</section>"
        )

    return [
        spiral_guide_html(data),
        ring("shape", kana_table_html(data) + derived_html(data)),
        ring("word", vocab_html(data)),
        ring("sense", cultural_html(data)),
        ring("root", origin_html(data) + spiral_closure_html(data)),
    ]


# 结构化数据视图注册表：data JSON 的 meta.kind → 渲染函数列表
KIND_VIEWS = {
    "gojuon": gojuon_views,
}


def module_data_blocks(lang_id, module):
    """ready 模块的结构化数据区块；无 JSON 或 kind 未注册时返回空(仅 prose)。"""
    mpath = os.path.join(DATA, lang_id, f"{module['id']}.json")
    if not os.path.exists(mpath):
        return []
    data = json.loads(read(mpath))
    kind = (data.get("meta") or {}).get("kind")
    if not kind:
        kind = module.get("kind") or module.get("id")
    view = KIND_VIEWS.get(kind)
    return view(data) if view else []


def teach_note():
    return (
        '<div class="teach-note" style="margin-top:2.2rem">'
        '<span data-zh><b>审校说明 ·</b> 教学例句（AI 起草）待母语者审校后再入正式语料；读音按标准语。</span>'
        '<span data-en><b>Review ·</b> Teaching sentences (AI-drafted) await native review before entering the formal corpus.</span>'
        "</div>"
    )


def cta_btn(href, zh, en):
    return (f'<div class="cta"><a class="btn" href="{e(href)}" data-zh>{e(zh)} &rarr;</a>'
            f'<a class="btn" href="{e(href)}" data-en>{e(en)} &rarr;</a></div>')


def rc_card(href, label):
    return f'<div class="cta" style="margin:1.2rem 0 0"><a class="btn" href="{e(href)}">{e(label)}</a></div>'


# ── 页面组装 ───────────────────────────────────────────────────
def page(css_rel, home, home_label, title, initlang, hero_html, body_html):
    return PAGE.format(
        title=title, css=css_rel, initlang=initlang, home=home, home_label=home_label,
        hero=hero_html, body=body_html,
    )


def render_hub(registry, hub_body, first_active):
    hero_html = hero(crumbs("语言叠织", "../../index.html", "语言根本", None),
                     "语种根本", "Language Roots",
                     "记读写 · 不离根本", "listen · read · write · stay rooted")
    body = render_hub_cards(registry, hub_body)
    if glossary_ready():
        body += glossary_card()
    body += cta_btn(f"{first_active}/", f"进入 {first_active}", "Enter")
    body += rc_card("../../index.html", "语言叠织 · 主页")
    return page("css/learning.css", "../../index.html", "Home",
                "语种根本 · Language Roots — 语言叠织", "lang-zh", hero_html, body)


def render_lang_index(entry, lang_meta, lang_body, first_ready=None):
    name_zh, name_en = entry["name_zh"], entry["name_en"]
    hero_html = hero(crumbs("语言根本", "../index.html", name_zh, None),
                     f"{name_zh} · 根本", f"{name_en} Roots",
                     entry["summary_zh"], entry["summary_en"])
    body = render_prose(lang_body) + module_grid(lang_meta.get("modules", []))
    if first_ready:
        body += cta_btn(f"{first_ready['id']}.html",
                        f"开始：{first_ready['name_zh']}",
                        f"Start: {first_ready['name_en']}")
    return page("../css/learning.css", "../index.html", "语言根本 | Roots",
                f"{name_zh} · 根本 — 语言叠织", "lang-zh", hero_html, body)


def render_module_page(entry, module, module_md):
    hero_html = hero(crumbs("语言根本", "../index.html",
                            entry["name_zh"], "../index.html",
                            module["name_zh"], None),
                     module["name_zh"], module["name_en"],
                     module["desc_zh"], module["desc_en"])
    body = render_prose(strip_h1(module_md))
    body += "".join(module_data_blocks(entry["id"], module))
    body += teach_note()
    title = f"{module['name_zh']} · {module['name_en']} — 语言叠织"
    return page("../css/learning.css", "../index.html", "语言根本 | Roots",
                title, "lang-zh", hero_html, body)


# ── 织网库（Core Glossary 概念权威）────────────────────────────
THREAD_KIND = {"derives_from": "沿根", "loaned_to": "借渡", "translates": "镜像"}


def load_core_glossary():
    """织网库概念权威 JSON；缺失/解析失败即报错（绝不静默出错）。"""
    if not os.path.exists(GLOSSARY_JSON):
        raise SystemExit(f"[glossary] 缺概念权威 {os.path.relpath(GLOSSARY_JSON)}")
    return json.loads(read(GLOSSARY_JSON))


def glossary_card():
    g = load_core_glossary()
    n = len(g.get("concepts", []))
    return (
        '<a class="card card-ready" href="glossary/" style="grid-column:1/-1">'
        f'<span class="glyph">织</span>'
        f'<span class="name" data-zh>织网库</span>'
        f'<span class="name" data-en>Concept Weave</span><br>'
        f'<span class="iso">{n} 概念 &times; 8 语</span>'
        f'<span class="summary" data-zh>一词而万语 · 水月心 · 词源织线</span>'
        f'<span class="summary" data-en>one word, many worlds · etymology woven</span>'
        '<span class="status ready" data-zh>织网</span>'
        '<span class="status ready" data-en>Weave</span></a>'
    )


def concept_threads(g, cid):
    """该概念的全部织线（双语 note）。"""
    out = []
    for t in g.get("threads", []):
        touched = t.get("from", "").endswith(":" + cid) or t.get("to", "").endswith(":" + cid)
        if not touched:
            continue
        kind = THREAD_KIND.get(t.get("kind"), t.get("kind", ""))
        out.append(
            f'<a class="wkind">{e(kind)}</a>'
            f'<span data-zh>{e(t.get("note_zh", ""))}</span>'
            f'<span data-en>{e(t.get("note_en", ""))}</span>'
        )
    return ("<div class=\"wthreads\">" + " &middot; ".join(out) + "</div>") if out else ""


def render_glossary_page():
    g = load_core_glossary()
    langs = g.get("languages", [])
    cards = []
    for c in g.get("concepts", []):
        terms = []
        for lang in langs:
            t = c["terms"].get(lang, {})
            roma = f'<span class="wr">{e(t.get("roma", ""))}</span>' if t.get("roma") else ""
            terms.append(
                f'<span class="wterm"><span class="wterml">{e(lang)}</span> '
                f'<span class="w">{e(t.get("word", ""))}</span>{roma}</span>'
            )
        cards.append(
            '<div class="wcard">'
            f'<div class="whead"><span class="wname" data-zh>{e(c["name_zh"])}</span>'
            f'<span class="wname" data-en>{e(c["name_en"])}</span>'
            f'<span class="wid">{e(c["id"])}</span>'
            '<span class="wtag">review pending</span></div>'
            f'<div class="words">{"".join(terms)}</div>'
            f'{concept_threads(g, c["id"])}'
            "</div>"
        )
    hero_html = hero(crumbs("语言根本", "../index.html", "织网库", None),
                     "织网库 · 概念", "Concept Weave", "一词而万语", "one word, many worlds")
    body = render_prose(strip_h1(read(GLOSSARY_MD)))
    body += f'<section class="wgrid">{"".join(cards)}</section>'
    body += teach_note()
    return page("../css/learning.css", "../index.html", "学习库 | Learning",
                "织网库 · Concept Weave — 语言叠织", "lang-zh", hero_html, body)


def glossary_ready():
    return os.path.exists(GLOSSARY_MD) and os.path.exists(GLOSSARY_JSON)


def load_registry():
    path = os.path.join(LANG, "README.md")
    registry, hub_body_md = parse_frontmatter(read(path))
    if registry is None or "languages" not in registry:
        raise SystemExit(f"[build] {os.path.relpath(path)} 缺 ---json--- frontmatter 或 languages 列表")
    return registry, hub_body_md


def langs_with_modules():
    """iterator: (entry, meta, body_md) 仅 active 语种"""
    registry, _ = load_registry()
    for entry in registry["languages"]:
        if entry.get("status") != "active":
            continue
        meta, body = parse_frontmatter(read(os.path.join(LANG, entry["id"], "README.md")))
        yield entry, meta, body


def build():
    registry, hub_body_md = load_registry()
    active = [x for x in registry["languages"] if x.get("status") == "active"]
    if not active:
        raise SystemExit("[build] 注册表无 active 语种，无法构建")
    hub_prose = render_prose(strip_h1(hub_body_md))

    pages = {os.path.join(OUT, "index.html"): render_hub(registry, hub_prose, active[0]["id"])}

    for entry, meta, body in langs_with_modules():
        modules = meta.get("modules", [])
        ready = [m for m in modules if m.get("status") == "ready"]
        base = os.path.join(OUT, entry["id"])
        pages[os.path.join(base, "index.html")] = render_lang_index(entry, meta, body,
                                                                    ready[0] if ready else None)
        for m in ready:
            md_path = os.path.join(LANG, entry["id"], f"{m['id']}.md")
            if os.path.exists(md_path):
                pages[os.path.join(base, f"{m['id']}.html")] = render_module_page(
                    entry, m, read(md_path))
    if glossary_ready():
        pages[os.path.join(OUT, "glossary", "index.html")] = render_glossary_page()
    return pages


# ── 校验（知识源）──────────────────────────────────────────────
def validate_glossary():
    """织网库 Core Glossary 结构校验（概念权威，绝不静默出错）。"""
    errors = []
    if not os.path.exists(GLOSSARY_JSON):
        errors.append("缺 core_glossary.json（织网库概念权威）")
        return errors
    try:
        g = json.loads(read(GLOSSARY_JSON))
    except ValueError as exc:
        errors.append(f"core_glossary.json 解析失败: {exc}")
        return errors
    langs = g.get("languages") or []
    if len(langs) < 2:
        errors.append("core_glossary languages 列表缺失或过短")
        return errors
    ids = []
    for c in g.get("concepts", []):
        cid = c.get("id")
        if not cid:
            errors.append("概念缺 id")
            continue
        ids.append(cid)
        for field in ("name_zh", "name_en"):
            if not c.get(field):
                errors.append(f"[{cid}] 缺字段 {field}")
        terms = c.get("terms") or {}
        missing = [l for l in langs if l not in terms]
        if missing:
            errors.append(f"[{cid}] 缺语种词位: {missing}")
        for lang, t in terms.items():
            if not isinstance(t, dict) or "word" not in t:
                errors.append(f"[{cid}/{lang}] 词位缺 word")
            if not isinstance(t, dict) or "roma" not in t:
                errors.append(f"[{cid}/{lang}] 词位缺 roma 键")
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    if dupes:
        errors.append(f"概念 id 重复: {dupes}")
    lang_set = set(langs)
    for s in g.get("scripts", []):
        if not s.get("id"):
            errors.append("script 缺 id")
            continue
        bad = [l for l in s.get("langs", []) if l not in lang_set]
        if bad:
            errors.append(f"[script {s['id']}] 语言不在注册: {bad}")
    for t in g.get("threads", []):
        if t.get("kind") not in THREAD_KIND:
            errors.append(f"[thread {t.get('id')}] kind 非法: {t.get('kind')}")
        for ref in (t.get("from"), t.get("to")):
            if not ref or not (ref.startswith("root:") or ":" in ref):
                errors.append(f"[thread {t.get('id')}] 引用格式非法: {ref!r}")
    if not g.get("meta", {}).get("review"):
        errors.append("core_glossary 缺 meta.review（审校状态必须声明）")
    return errors


def validate_sources():
    """返回错误消息列表（空 = 通过）。节奏：绝不静默出错。"""
    errors = []

    registry, hub_body = load_registry()
    langs = registry["languages"]
    if not langs:
        errors.append("hub frontmatter 缺 languages 列表")

    ids = [l.get("id") for l in langs if l.get("id")]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    if dupes:
        errors.append(f"语种 id 重复: {dupes}")

    for l in langs:
        lid = l.get("id")
        for field in ("name_zh", "name_en", "iso", "glyph", "summary_zh", "summary_en"):
            if not l.get(field):
                errors.append(f"[{lid or '?'}] 缺字段 {field}")
        if l.get("status") == "active":
            if not l.get("href"):
                errors.append(f"[{lid}] active 语种缺 href")
            # active 语种必有 README；planned 语种不允许出现学习页文件
            readme = os.path.join(LANG, lid, "README.md")
            if not os.path.exists(readme):
                errors.append(f"[{lid}] active 语种缺 {lid}/README.md")
            meta, body = parse_frontmatter(read(readme))
            if meta is None:
                errors.append(f"[{lid}] README.md 无 frontmatter")
                continue
            modules = meta.get("modules", [])
            m_ids = [m.get("id") for m in modules]
            m_dupes = sorted({i for i in m_ids if m_ids.count(i) > 1})
            if m_dupes:
                errors.append(f"[{lid}] 模块 id 重复: {m_dupes}")
            for m in modules:
                for field in ("name_zh", "name_en", "desc_zh", "desc_en"):
                    if not m.get(field):
                        errors.append(f"[{lid}/{m.get('id')}] 缺模块字段 {field}")
                if m.get("status") == "ready":
                    if m.get("href") != f"{m['id']}.html":
                        errors.append(f"[{lid}/{m['id']}] ready 模块 href 应为 {m['id']}.html")
                    mdp = os.path.join(LANG, lid, f"{m['id']}.md")
                    if not os.path.exists(mdp):
                        errors.append(f"[{lid}/{m['id']}] ready 模块缺页面源 {m['id']}.md")
                    else:
                        validate_md_bilingual(mdp, errors, lid, m["id"])
                    jpath = os.path.join(DATA, lid, f"{m['id']}.json")
                    if os.path.exists(jpath):
                        validate_module_json(jpath, errors, lid, m["id"])
                else:  # planned
                    if m.get("href") not in (None, "", "#future"):
                        errors.append(f"[{lid}/{m['id']}] planned 模块不应有实际 href")
            if body and not body.strip():
                errors.append(f"[{lid}] README 正文为空")
    errors += validate_glossary()
    if not os.path.exists(GLOSSARY_MD):
        errors.append("缺 glossary.md（织网库散文页源）")
    else:
        validate_md_bilingual(GLOSSARY_MD, errors, "glossary", "index")
    return errors


def validate_md_bilingual(path, errors, lid, mid):
    text = read(path)
    zh = len(re.findall(r"^\s*<!--\s*zh\s*-->", text, re.M))
    en = len(re.findall(r"^\s*<!--\s*en\s*-->", text, re.M))
    if zh != en:
        errors.append(f"[{lid}/{mid}] 双语标记不平衡 zh={zh} en={en}")
    if strip_h1(text) == text and not re.match(r"^#\s+.+", text):
        errors.append(f"[{lid}/{mid}] 缺 H1 标题行")


def validate_module_json(path, errors, lid, mid):
    try:
        data = json.loads(read(path))
    except ValueError as exc:
        errors.append(f"[{lid}/{mid}] JSON 解析失败: {exc}")
        return
    kind = (data.get("meta") or {}).get("kind")
    if kind and kind not in KIND_VIEWS:
        errors.append(f"[{lid}/{mid}] JSON meta.kind={kind} 未注册渲染视图(KIND_VIEWS)，页面将只有 prose")
    if "chart" in data:
        chart = data["chart"]
        for ri, row in enumerate(chart.get("rows", [])):
            for ci, c in enumerate(row.get("cells", [])):
                keys = set(c)
                if c.get("void"):
                    if keys - {"void"}:
                        errors.append(f"[{lid}/{mid}] 第{ri}行{ci}列 void 单元携带多余键 {sorted(keys - {'void'})}")
                    continue
                for field in ("h", "kat", "r"):
                    if not c.get(field):
                        errors.append(f"[{lid}/{mid}] 第{ri}行{ci}列缺字段 {field}")
    if "vocab" in data:
        for i, v in enumerate(data["vocab"]):
            for field in ("h", "kanji", "kana", "rom", "meaning_zh", "meaning_en", "sent", "sent_rom", "tr_zh", "tr_en", "r", "kat"):
                if not v.get(field):
                    errors.append(f"[{lid}/{mid}] 词表第{i}条缺字段 {field}")


# ── 产物校验 ───────────────────────────────────────────────────
def check_outputs(pages):
    ok = True
    expected = set(pages.keys())
    for path, text in pages.items():
        if not os.path.exists(path):
            print(f"[check] MISSING {path}")
            ok = False
            continue
        needles = ["data-bit"]
        rel = os.path.relpath(path, OUT)
        if "data-bit" not in text:
            ok = False
            print(f"[check] {rel} 缺 data-bit")
        for tag in ("div", "table", "span", "a", "section"):
            delta = text.count(f"<{tag}") - text.count(f"</{tag}>")
            if delta:
                print(f"[check] {rel} 标签<{tag}>不平衡 ±{delta}")
                ok = False
        if len(text) < 2000:
            print(f"[check] {rel} 内容过短")
            ok = False
    # 陈旧产物检测：OUT 下存在但本次未声明的 .html
    stale = set()
    for root, _dirs, files in os.walk(OUT):
        for fn in files:
            if fn.endswith(".html"):
                full = os.path.join(root, fn)
                if full not in expected:
                    stale.add(full)
    if stale:
        ok = False
        for s in sorted(stale):
            print(f"[check] 陈旧产物(不在本次构建): {s}")
    return ok


# ── sqlite 索引 ───────────────────────────────────────────────
def sync_sqlite(registry, langs_modules, db_path=None):
    import sqlite3
    db_path = db_path or os.path.join(DATA, "learning.db")
    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    con = sqlite3.connect(db_path)
    cur = con.cursor()
    cur.execute("""CREATE TABLE IF NOT EXISTS meta(
        key TEXT PRIMARY KEY, value TEXT)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS languages(
        id TEXT PRIMARY KEY, glyph TEXT, name_zh TEXT, name_en TEXT,
        iso TEXT, status TEXT, summary_zh TEXT, summary_en TEXT, href TEXT)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS modules(
        id TEXT, lang TEXT, href TEXT, status TEXT,
        name_zh TEXT, name_en TEXT, PRIMARY KEY(id, lang))""")
    cur.execute("""CREATE TABLE IF NOT EXISTS chart_cells(
        lang TEXT, module TEXT, row TEXT, col INTEGER, h TEXT, kata TEXT,
        roma TEXT, note TEXT, PRIMARY KEY(lang, module, row, col))""")
    cur.execute("""CREATE TABLE IF NOT EXISTS vocab(
        lang TEXT, module TEXT, id TEXT, hira TEXT, kata TEXT, roma TEXT,
        kanji TEXT, kana TEXT, meaning_zh TEXT, meaning_en TEXT,
        sentence TEXT, sent_rom TEXT, tr_zh TEXT, tr_en TEXT,
        PRIMARY KEY(lang, module, id))""")
    cur.execute("""CREATE TABLE IF NOT EXISTS concepts(
        id TEXT PRIMARY KEY, name_zh TEXT, name_en TEXT, probe INTEGER DEFAULT 0)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS concept_terms(
        concept TEXT, lang TEXT, word TEXT, roma TEXT,
        PRIMARY KEY(concept, lang))""")
    cur.execute("""CREATE TABLE IF NOT EXISTS scripts(
        id TEXT PRIMARY KEY, name_zh TEXT, name_en TEXT,
        note_zh TEXT, note_en TEXT, langs TEXT)""")
    cur.execute("""CREATE TABLE IF NOT EXISTS threads(
        id TEXT PRIMARY KEY, kind TEXT, from_ref TEXT, to_ref TEXT,
        note_zh TEXT, note_en TEXT)""")
    cur.execute("DELETE FROM languages")
    cur.execute("DELETE FROM modules")
    cur.execute("DELETE FROM chart_cells")
    cur.execute("DELETE FROM vocab")
    _sync_glossary(cur)
    cur.executemany("INSERT INTO languages VALUES(:id,:glyph,:name_zh,:name_en,:iso,:status,:summary_zh,:summary_en,:href)",
                    [{"id": l["id"], **{k: l.get(k, "") for k in ("glyph", "name_zh", "name_en", "iso", "status", "summary_zh", "summary_en", "href")}}
                     for l in registry["languages"]])
    for lang_id, modules in langs_modules.items():
        for m in modules:
            cur.execute("INSERT INTO modules VALUES(?,?,?,?,?,?)",
                        (m["id"], lang_id, m.get("href", ""), m.get("status", "planned"),
                         m.get("name_zh", ""), m.get("name_en", "")))
            jpath = os.path.join(DATA, lang_id, f"{m['id']}.json")
            if os.path.exists(jpath):
                data = json.loads(read(jpath))
                _sync_chart(cur, lang_id, m["id"], data)
                _sync_vocab(cur, lang_id, m["id"], data)
    cur.execute("INSERT OR REPLACE INTO meta VALUES('schema_version','1')")
    cur.execute("INSERT OR REPLACE INTO meta VALUES('builder','build_learning.py')")
    con.commit()
    con.close()
    print(f"[db] 学习库索引已同步: {db_path}")


def _sync_glossary(cur):
    """织网库 Core Glossary → concepts/concept_terms/scripts/threads 表。"""
    g = load_core_glossary()
    for c in g.get("concepts", []):
        cur.execute("INSERT OR REPLACE INTO concepts VALUES(?,?,?,0)",
                    (c["id"], c.get("name_zh", ""), c.get("name_en", "")))
        for lang, t in (c.get("terms") or {}).items():
            cur.execute("INSERT OR REPLACE INTO concept_terms VALUES(?,?,?,?)",
                        (c["id"], lang, t.get("word", ""), t.get("roma", "")))
    for s in g.get("scripts", []):
        cur.execute("INSERT OR REPLACE INTO scripts VALUES(?,?,?,?,?,?)",
                    (s["id"], s.get("name_zh", ""), s.get("name_en", ""),
                     s.get("note_zh", ""), s.get("note_en", ""),
                     ",".join(s.get("langs", []))))
    for t in g.get("threads", []):
        cur.execute("INSERT OR REPLACE INTO threads VALUES(?,?,?,?,?,?)",
                    (t["id"], t["kind"], t["from"], t["to"],
                     t.get("note_zh", ""), t.get("note_en", "")))


def _sync_chart(cur, lang_id, module_id, data):
    chart = data.get("chart") or {}
    for ri, row in enumerate(chart.get("rows", [])):
        for ci, c in enumerate(row.get("cells", [])):
            note = ""
            if c.get("void"):
                note = "void"
            elif c.get("particle"):
                note = "particle"
            cur.execute(
                "INSERT OR REPLACE INTO chart_cells VALUES(?,?,?,?,?,?,?,?)",
                (lang_id, module_id, row.get("row", ""), ci,
                 (c.get("h") or ""), (c.get("kat") or ""), (c.get("r") or ""), note))
    n = chart.get("n")
    if isinstance(n, dict):
        cur.execute(
            "INSERT OR REPLACE INTO chart_cells VALUES(?,?,?,?,?,?,?,?)",
            (lang_id, module_id, "n", 0,
             (n.get("h") or ""), (n.get("kat") or ""), (n.get("r") or ""), ""))


def _sync_vocab(cur, lang_id, module_id, data):
    for v in data.get("vocab", []):
        cur.execute(
            "INSERT OR REPLACE INTO vocab VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (lang_id, module_id, v.get("h", ""), v.get("h", ""), v.get("kat", ""), v.get("r", ""),
             v.get("kanji", ""), v.get("kana", ""), v.get("meaning_zh", ""), v.get("meaning_en", ""),
             v.get("sent", ""), v.get("sent_rom", ""), v.get("tr_zh", ""), v.get("tr_en", "")))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--validate", action="store_true", help="校验知识源")
    ap.add_argument("--db", action="store_true", help="同步 sqlite 查询索引")
    ap.add_argument("--check", action="store_true", help="源校验 + 产物校验")
    args = ap.parse_args()

    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    if args.validate or args.check:
        errs = validate_sources()
        if errs:
            print("[validate] 发现 %d 处错误:" % len(errs))
            for er in errs:
                print("  [ERR]", er)
            sys.exit(1)
        print("[validate] 知识源通过")

    os.makedirs(os.path.dirname(CSS_OUT), exist_ok=True)
    if os.path.exists(CSS_SRC) and read(CSS_SRC).strip():
        write(CSS_OUT, read(CSS_SRC))

    pages = build()
    for path, text in pages.items():
        write(path, text)
    print(f"[build] 已生成 {len(pages)} 页 -> {OUT}")

    if args.db:
        registry, _ = load_registry()
        langs_modules = {}
        for entry in registry["languages"]:
            if entry.get("status") != "active":
                continue
            meta, _body = parse_frontmatter(
                read(os.path.join(LANG, entry["id"], "README.md")))
            langs_modules[entry["id"]] = (meta or {}).get("modules", [])
        sync_sqlite(registry, langs_modules)

    if args.check:
        ok = check_outputs(pages)
        sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()