#!/usr/bin/env python3
"""Build the combined reader's edition: bilingual Comment as 导读/foreword + full bilingual paper.

Why a build script instead of a hand-assembled file: ai_and_math.md is the *source
of record* for the full paper, and comment_draft.md §A is the source of record for the
English Comment (comment_draft_zh.md for its Chinese). Copying them by hand into one
document would create a second truth that silently drifts. So this script *assembles*
`reader_edition.md` from those three files at build time, and `--check` re-assembles
and compares, failing if the committed edition no longer matches its sources
(harness MC-W2/R-D: what a machine can keep consistent, keep consistent by machine;
信息无损: nothing is edited in the merge, only concatenated with generated front matter).

Layout of the generated edition:
  front matter (provenance + 导读 foreword + Comment->paper section map)
  Part I  简版·导读 / The Comment (reader's guide):  <!-- en --> English, <!-- zh --> Chinese
  Part II 完整版 / The full paper (verbatim from ai_and_math.md)

Run:  python build_reader.py            # (re)generate reader_edition.md
      python build_reader.py --check    # exit 1 if the file is stale vs its sources
Deps: none (stdlib).
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent            # .../essays/submission
ESSAYS = HERE.parent                                # .../essays
COMMENT_EN = HERE / "comment_draft.md"
COMMENT_ZH = HERE / "comment_draft_zh.md"
PAPER = ESSAYS / "ai_and_math.md"
OUT = HERE / "reader_edition.md"

ZH_BEGIN = "<!-- BODY-ZH-BEGIN -->"
ZH_END = "<!-- BODY-ZH-END -->"


def english_comment():
    """Slice the §A manuscript body out of comment_draft.md (title line to the rule
    before '## B'), trimmed of the trailing horizontal rule."""
    c = COMMENT_EN.read_text(encoding="utf-8")
    start = c.index("### Mathematics is not in crisis")
    end = c.index("\n## B ", start)
    seg = c[start:end].rstrip()
    while seg.endswith("---"):
        seg = seg[:-3].rstrip()
    return seg


def chinese_comment():
    z = COMMENT_ZH.read_text(encoding="utf-8")
    start = z.index(ZH_BEGIN) + len(ZH_BEGIN)
    end = z.index(ZH_END)
    return z[start:end].strip()


def full_paper():
    return PAPER.read_text(encoding="utf-8").strip()


def front_matter():
    """Generated 导读: framing + the Comment->paper map. Authored here (not in the
    source files) so the two source-of-record documents stay untouched."""
    return """# 导读与全编 · 数学的危机，还是数学家的危机？
# Reader's Edition · A Crisis of Mathematics, or of the Mathematicians?

> **Status 状态**: A single-document reading edition. **AI-drafted, unreviewed** (harness §I.6). **Generated by [`build_reader.py`](build_reader.py); do not edit by hand.** The Comment text here is copied from [`comment_draft.md`](comment_draft.md) §A (English) and [`comment_draft_zh.md`](comment_draft_zh.md) (Chinese); the full paper is copied verbatim from [`../ai_and_math.md`](../ai_and_math.md), which **remains the source of record**. To refresh after editing any source: `python build_reader.py`; to verify this file is current: `python build_reader.py --check`.
>
> **How to read 阅读法**: Part I is the *Comment* — a ~1,670-word argument written for a general scientific readership. It is also the **导读 (reading guide)** for Part II: every claim it makes is a compressed version of a claim the full paper argues at length. Read Part I for the shape of the case; go to Part II (and the section map below) for the evidence, the rival explanations, the audit apparatus, and the philosophy.

## 前沿 · 导读 · Foreword

The short piece and the long piece are one argument at two resolutions. The Comment stakes a single predictive claim — that where controversy lands in AI mathematics is a function of the **certification regime**, not of difficulty — and hands off, in its own last paragraph, to a census that must test what eleven publicity-selected events cannot. The paper supplies everything the Comment has to compress: the literature reconstruction (1954–2026), the five rival explanations and the four observations that would refute them, the eleven-event coding with its two audit tables, the signifier/signified framework and its limits, the sociology of the ladder, and the demarcation criterion. Where the Comment says "meaning, adjudicated by people," §6 says why in one line: the kernel checks proof terms; what a statement *means* is a separate task.

### Comment → paper, section by section

| The Comment's move | Its home in the full paper |
|---|---|
| The three certification regimes (machine / hybrid / community) | §3.1 (five categories) · §11.2 (the ordered decision rule) |
| "Regime, not difficulty" and the rival it cannot exclude | §3.3 (H1–H5) · §4 (the ordering) |
| The eleven events, 1/6 vs 3/5, Fisher P ≈ 0.24 | §4 (evidential base) · §11.4–11.5 (Table 1; what the coding yields and does not) |
| Navier–Stokes: a dispute about which sentence was proved | §4.9 (the top rung) · §6.5 (a proof of the wrong sentence) |
| 1977 four-colour, Tymoczko, DeMillo–Lipton–Perlis, Merton | §2.2 · §2.4 · §2.5 (the three literature streams) |
| The shared syllogism and its false minor premise | §3.2 (the core argument, reconstructed) |
| Disclose / designate the certifier / register admissibility | §10.2–10.3 (the correct naming) · §11.8 (statements) |
| "Faithful only to itself" (left implicit in the Comment) | §6 (signifier and signified, the limits of formal exactness) |

---

# Part I · 简版 · 导读 / The Comment as Reader's Guide

A *Nature*-format Comment: English body, then its Chinese rendering. Figures, the coding CSV, the reliability appendix, and the reference list live in [`comment_draft.md`](comment_draft.md) §§B–D and are not repeated here.

<!-- en -->"""


def assemble():
    parts = [
        front_matter(),
        english_comment(),
        "\n<!-- zh -->\n\n" + chinese_comment(),
        "\n\n---\n\n# Part II · 完整版 / The Full Paper\n\n"
        "Verbatim from [`../ai_and_math.md`](../ai_and_math.md) (source of record), bilingual throughout.\n\n---\n\n"
        + full_paper(),
    ]
    return "\n\n".join(p.strip("\n") for p in parts) + "\n"


def main(argv):
    generated = assemble()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current == generated:
            print("PASS: reader_edition.md is current with its three source files")
            return 0
        print("FAIL: reader_edition.md is STALE vs its sources — run `python build_reader.py`",
              file=sys.stderr)
        return 1
    OUT.write_text(generated, encoding="utf-8")
    n_lines = generated.count("\n") + 1
    print(f"wrote {OUT.name}: {n_lines} lines, "
          f"{len(english_comment().split())} EN comment words, "
          f"full paper embedded from {PAPER.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
